DayZ Scripts: TestHarness Class Reference
TestHarness Class Reference
Script Testing Framework
Collection and main interface of the Testing framework.
Static Private Member Functions
proto static native bool Run ()
static proto string Report ()
Generates a xml report.
proto static native int GetNSuites ()
Returns number of test suites.
proto static native TestSuite GetSuite (int handle)
Returns a test suite.
proto static native TestSuite ActiveSuite ()
Returns currently active TestSuite or null when none is active.
proto static native bool Finished ()
Returns true when all tests and suites finished.
proto static native void Begin ()
Starts up the testing process and initializes the structures.
proto static native void End ()
Finalizes the testing process.
Detailed Description
Collection and main interface of the Testing framework.
Member Function Documentation
ActiveSuite()
proto static native TestSuite ActiveSuite () static private
Returns currently active TestSuite or null when none is active.
Begin()
proto static native void Begin () static private
Starts up the testing process and initializes the structures.
Referenced by AutotestRunner::Start().
End()
proto static native void End () static private
Finalizes the testing process.
Referenced by AutotestRunner::Update().
Finished()
proto static native bool Finished () static private
Returns true when all tests and suites finished.
Referenced by AutotestRunner::Update().
GetNSuites()
proto static native int GetNSuites () static private
Returns number of test suites.
Referenced by AutotestRunner::Start().
GetSuite()
proto static native TestSuite GetSuite (int handle) static private
Returns a test suite.
Referenced by AutotestRunner::Start().
Report()
static proto string Report () static private
Generates a xml report.
Referenced by AutotestRunner::Update().
Run()
proto static native bool Run () static private
Starts the testing process. Returns true when all tests have finished. If some of them are still in progress false is reported.
Referenced by AutotestRunner::Update().
The documentation for this class was generated from the following file:
P:/scripts/2_GameLib/tests/TestingFramework.c