DayZ Scripts: P:/scripts/5_Mission/GUI/ScriptConsoleCameraTab.c File Reference
ScriptConsoleCameraTab.c File Reference
Data Structures
class ScriptConsoleCameraValues
class ScriptConsoleCameraTab
Functions
static ScriptConsoleCameraValues GetScriptConsoleValues ()
Variables
class ScriptConsoleCameraValues s_ScriptConsoleValues
Function Documentation
GetScriptConsoleValues()
static ScriptConsoleCameraValues GetScriptConsoleValues () static
References s_ScriptConsoleValues.
Referenced by ScriptConsoleCameraTab::LoadDOFPreset(), ScriptConsoleCameraTab::ResetDOF(), ScriptConsoleCameraTab::SaveDOFPreset(), ScriptConsoleCameraTab::ScriptConsoleCameraTab(), ScriptConsoleCameraTab::SetDOF(), ScriptConsoleCameraTab::ToggleValueEditMode(), ScriptConsoleCameraTab::UpdateBlur(), ScriptConsoleCameraTab::UpdateDOFSliders(), ScriptConsoleCameraTab::UpdateFocusDepthOffset(), ScriptConsoleCameraTab::UpdateFocusDistance(), ScriptConsoleCameraTab::UpdateFocusLength(), ScriptConsoleCameraTab::UpdateFocusLengthNear(), and ScriptConsoleCameraTab::UpdateFOV().
Variable Documentation
s_ScriptConsoleValues
class ScriptConsoleCameraValues s_ScriptConsoleValues
Referenced by GetScriptConsoleValues().