DayZ Scripts: Misc_TirePile_Burning_DE Class Reference
Misc_TirePile_Burning_DE Class Reference
Private Member Functions
override void EEInit ()
override void EEDelete (EntityAI parent)
override void DeferredInit ()
protected void CreateAreaDamage ()
protected void DestroyAreaDamage ()
Private Attributes
private const float TIMER_HEATING_UPDATE_INTERVAL = 2
private const float PARAM_HEAT_RADIUS = 6
private const float PARAM_FULL_HEAT_RADIUS = 4
private const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25
protected TirePileLight m_Light
maximum value for temperature that will be transfered to player (environment)
protected Particle m_ParticleFire
protected EffectSound m_SoundFireLoop
protected ref UniversalTemperatureSource m_UTSource
protected ref UniversalTemperatureSourceSettings m_UTSSettings
protected ref UniversalTemperatureSourceLambdaConstant m_UTSLTirePile
protected ref AreaDamageManager m_AreaDamage
Member Function Documentation
CreateAreaDamage()
protected void CreateAreaDamage () inline private
References DestroyAreaDamage(), AreaDamageComponentTypes::HITZONE, and m_AreaDamage.
Referenced by DeferredInit().
DeferredInit()
override void DeferredInit () inline private
References CreateAreaDamage(), GetGame(), and m_AreaDamage.
DestroyAreaDamage()
protected void DestroyAreaDamage () inline private
References m_AreaDamage.
Referenced by CreateAreaDamage(), and EEDelete().
EEDelete()
override void EEDelete (EntityAI parent) inline private
References DestroyAreaDamage(), GetGame(), m_Light, m_ParticleFire, m_SoundFireLoop, m_UTSource, EffectSound::SoundStop(), and Particle::Stop().
EEInit()
override void EEInit () inline private
References GetGame(), GameConstants::ITEM_TEMPERATURE_NEUTRAL_ZONE_MIDDLE, m_Light, m_ParticleFire, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, m_SoundFireLoop, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureItemCap, UniversalTemperatureSourceSettings::m_Updateable, UniversalTemperatureSourceSettings::m_UpdateInterval, m_UTSLTirePile, m_UTSource, m_UTSSettings, PARAM_FULL_HEAT_RADIUS, PARAM_HEAT_RADIUS, PARAM_MAX_TRANSFERED_TEMPERATURE, ParticleManager(), TIMER_HEATING_UPDATE_INTERVAL, ParticleList::TIREPILE_FIRE, and Vector().
Field Documentation
m_AreaDamage
protected ref AreaDamageManager m_AreaDamage private
Referenced by CreateAreaDamage(), DeferredInit(), and DestroyAreaDamage().
m_Light
protected TirePileLight m_Light private
maximum value for temperature that will be transfered to player (environment)
Referenced by EEDelete(), and EEInit().
m_ParticleFire
protected Particle m_ParticleFire private
Referenced by EEDelete(), and EEInit().
m_SoundFireLoop
protected EffectSound m_SoundFireLoop private
Referenced by EEDelete(), and EEInit().
m_UTSLTirePile
protected ref UniversalTemperatureSourceLambdaConstant m_UTSLTirePile private
Referenced by EEInit().
m_UTSource
protected ref UniversalTemperatureSource m_UTSource private
Referenced by EEDelete(), and EEInit().
m_UTSSettings
protected ref UniversalTemperatureSourceSettings m_UTSSettings private
Referenced by EEInit().
PARAM_FULL_HEAT_RADIUS
private const float PARAM_FULL_HEAT_RADIUS = 4 private
Referenced by EEInit().
PARAM_HEAT_RADIUS
private const float PARAM_HEAT_RADIUS = 6 private
Referenced by EEInit().
PARAM_MAX_TRANSFERED_TEMPERATURE
private const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25 private
Referenced by EEInit().
TIMER_HEATING_UPDATE_INTERVAL
private const float TIMER_HEATING_UPDATE_INTERVAL = 2 private
Referenced by EEInit().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Building/Specific/Misc_TirePile_Burning.c