DayZ Scripts: P:/scripts/4_World/Classes/SoundHandlers/ItemSoundHandler.c File Reference
ItemSoundHandler.c File Reference
Data Structures
class SoundParameters
Functions
void ItemSoundHandler (ItemBase parent)
void ~ItemSoundHandler ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void PlayItemSoundClient (int id)
void StopItemSoundClient (int id)
void AddSound (int sound, string soundset, SoundParameters params=null)
Variables
class SoundParameters m_Parent
protected ref map< int, ref EffectSound > m_PlayingSounds
protected ref map< int, string > m_AvailableSoundsets
protected ref map< int, ref SoundParameters > m_SoundParamsMap
Function Documentation
AddSound()
void AddSound (int sound, string soundset, SoundParameters params = null)
References m_AvailableSoundsets, and m_SoundParamsMap.
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
References m_AvailableSoundsets, m_PlayingSounds, and m_SoundParamsMap.
ItemSoundHandler()
void ItemSoundHandler (ItemBase parent)
References Managed::Init(), and m_Parent.
Referenced by InventoryItem::GetItemSoundHandler(), InitItemSounds(), InventoryItem::InitItemSounds(), Barrel_ColorBase::InitItemSounds(), FireplaceBase::InitItemSounds(), ShippingContainerKeys_ColorBase::InitItemSounds(), and ItemBase::InitItemSounds().
PlayItemSoundClient()
void PlayItemSoundClient (int id)
References Empty, Debug::Log(), m_AvailableSoundsets, SoundParameters::m_FadeIn, SoundParameters::m_FadeOut, SoundParameters::m_Loop, m_Parent, m_PlayingSounds, m_SoundParamsMap, SEffectManager::PlaySound(), SEffectManager::PlaySoundCachedParams(), and EffectSound::SetAutodestroy().
StopItemSoundClient()
void StopItemSoundClient (int id)
References GetGame(), m_PlayingSounds, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
~ItemSoundHandler()
void ~ItemSoundHandler ()
References m_PlayingSounds.
Variable Documentation
m_AvailableSoundsets
protected ref map<int, string> m_AvailableSoundsets
Referenced by AddSound(), Init(), and PlayItemSoundClient().
m_Parent
class SoundParameters m_Parent
m_PlayingSounds
protected ref map<int, ref EffectSound> m_PlayingSounds
Referenced by Init(), PlayItemSoundClient(), StopItemSoundClient(), and ~ItemSoundHandler().
m_SoundParamsMap
protected ref map<int, ref SoundParameters> m_SoundParamsMap
Referenced by AddSound(), Init(), and PlayItemSoundClient().