DayZ Scripts: TerritoryFlag Class Reference
TerritoryFlag Class Reference
Private Member Functions
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
override void OnSpawnByObjectSpawner (ITEM_SpawnerObject item)
override void FullyBuild ()
Member Function Documentation
FullyBuild()
override void FullyBuild () inline private
References AT_BUILD_PART, CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CreateConstructionKit(), CGame::GetCallQueue(), GetConstruction(), GetGame(), ConstructionPart::GetId(), ConstructionPart::IsBase(), RegisterActionForSync(), RegisterPartForSync(), ResetActionSyncData(), SetBaseState(), SetPartFromSyncData(), SynchronizeBaseState(), UpdateNavmesh(), and UpdateVisuals().
Referenced by OnSpawnByObjectSpawner().
OnPartDestroyedServer()
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false) inline private
OnPartDismantledServer()
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id) inline private
OnSpawnByObjectSpawner()
override void OnSpawnByObjectSpawner (ITEM_SpawnerObject item) inline private
References ITEM_SpawnerObject::customString, string::Empty, and FullyBuild().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/BaseBuildingBase/StaticFlagPole.c