DayZ Scripts: Torch_Video Class Reference
Torch_Video Class Reference
Private Member Functions
void SetEnablePtc ()
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
override void SetActions ()
Private Attributes
protected float PARTICLE_DELAY = 15000
protected bool m_EnablePtc
Member Function Documentation
OnWork()
override void OnWork (float consumed_energy) inline private
References m_EnablePtc.
OnWorkStart()
override void OnWorkStart () inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), PARTICLE_DELAY, and SetEnablePtc().
OnWorkStop()
override void OnWorkStop () inline private
References CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), GetGame(), m_EnablePtc, ScriptCallQueue::Remove(), and SetEnablePtc().
SetActions()
override void SetActions () inline private
References AddAction().
SetEnablePtc()
void SetEnablePtc () inline private
References m_EnablePtc.
Referenced by OnWorkStart(), and OnWorkStop().
Field Documentation
m_EnablePtc
protected bool m_EnablePtc private
Referenced by OnWork(), OnWorkStop(), and SetEnablePtc().
PARTICLE_DELAY
protected float PARTICLE_DELAY = 15000 private
Referenced by OnWorkStart().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Torch_Video.c