DayZ Scripts: OptionSelectorSliderSetup Class Reference
OptionSelectorSliderSetup Class Reference
This Option Selector handles a Slider Marker, which basically has 2 sliders One slider is for selecting the value, and the other slider is for displaying some other value/ information.
Private Member Functions
void OptionSelectorLevelMarker (Widget parent, float value, ScriptedWidgetEventHandler parentMenu, bool disabled, float min, float max)
override void Enable ()
override void Disable ()
void SetSlider2Value (float value)
override bool OnUpdate (Widget w)
void OptionSelectorSlider (Widget parent, float value, ScriptedWidgetEventHandler parent_menu, bool disabled, float min, float max, bool showEditbox=false)
void SetValueText ()
void Refresh (float defaultValue=-1)
float GetRangePercantageByValue ()
override bool OnChange (Widget w, int x, int y, bool finished)
bool Changed ()
bool IsValidEditboxValue (string text)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override bool IsFocusable (Widget w)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void SetActiveOption ()
void UpdateActiveOption ()
void Update ()
bool IsValueTextVisible ()
Private Attributes
protected SliderWidget m_Slider2
protected bool m_Changed
protected EditBoxWidget m_ValueText
protected bool m_ShowEditbox
protected float m_LastValue
Detailed Description
This Option Selector handles a Slider Marker, which basically has 2 sliders One slider is for selecting the value, and the other slider is for displaying some other value/ information.
Parameters
m_Slider2 other slider value, which can be used to convery some other info to the player
Member Function Documentation
Changed()
bool Changed () inline private
References m_Changed.
Disable()
override void Disable () inline private
Enable()
override void Enable () inline private
Referenced by OptionSelectorLevelMarker(), OptionSelectorSlider(), and ScriptConsoleSelector::ScriptConsoleSelector().
GetRangePercantageByValue()
float GetRangePercantageByValue () inline private
References GetValue(), m_MaxValue, and m_MinValue.
Referenced by SetValueText().
IsFocusable()
override bool IsFocusable (Widget w) inline private
References m_Parent.
IsValidEditboxValue()
bool IsValidEditboxValue (string text) inline private
References string::Get(), string::Length(), and string::ToInt().
Referenced by OnChange().
IsValueTextVisible()
bool IsValueTextVisible () inline private
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished) inline private
References GetValue(), IsValidEditboxValue(), m_MaxValue, m_MinValue, Refresh(), and SetValueText().
OnDoubleClick()
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
References ARGB(), GetValue(), SetActiveOption(), and SetFocus().
OnFocus()
override bool OnFocus (Widget w, int x, int y) inline private
References GetValue(), m_Parent, SetActiveOption(), UpdateActiveOption(), x, and y.
Referenced by OptionSelectorBase::OnMouseEnter().
OnFocusLost()
override bool OnFocusLost (Widget w, int x, int y) inline private
References UpdateActiveOption(), x, and y.
Referenced by OptionSelectorBase::OnMouseLeave().
OnMouseLeave()
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
References Refresh(), x, and y.
OnUpdate()
override bool OnUpdate (Widget w) inline private
OptionSelectorLevelMarker()
void OptionSelectorLevelMarker (Widget parent, float value, ScriptedWidgetEventHandler parentMenu, bool disabled, float min, float max) inline private
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_MaxValue, m_MinValue, m_Parent, m_Root, SetSlider2Value(), and SetValue().
OptionSelectorSlider()
void OptionSelectorSlider (Widget parent, float value, ScriptedWidgetEventHandler parent_menu, bool disabled, float min, float max, bool showEditbox = false) inline private
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_MaxValue, m_MinValue, m_Parent, m_Root, SetValue(), and SetValueText().
Refresh()
void Refresh (float defaultValue = -1) inline private
References SetValue(), and SetValueText().
SetActiveOption()
void SetActiveOption () inline private
Referenced by OnDoubleClick(), and OnFocus().
SetSlider2Value()
void SetSlider2Value (float value) inline private
Referenced by OptionSelectorLevelMarker().
SetValueText()
void SetValueText () inline private
References GetRangePercantageByValue(), and float::ToString().
Referenced by OnChange(), OptionSelectorSlider(), and Refresh().
Update()
void Update () inline private
References ARGB(), and Refresh().
UpdateActiveOption()
void UpdateActiveOption () inline private
Referenced by OnFocus(), and OnFocusLost().
Field Documentation
m_Changed
protected bool m_Changed private
Referenced by Changed().
m_LastValue
protected float m_LastValue private
m_ShowEditbox
protected bool m_ShowEditbox private
m_Slider2
protected SliderWidget m_Slider2 private
m_ValueText
protected EditBoxWidget m_ValueText private
The documentation for this class was generated from the following files:
P:/scripts/5_Mission/GUI/NewUI/OptionSelectorLevelMarker.c
P:/scripts/5_Mission/GUI/NewUI/OptionSelectorSlider.c