DayZ Scripts: AutotestRunner Class Reference
AutotestRunner Class Reference
Static Private Member Functions
static bool IsRunning ()
static bool IsDone ()
static void Start ()
static void Update (float deltaTime)
Static Private Attributes
static private bool m_IsRunning
static private bool m_IsDone
Member Function Documentation
IsDone()
static bool IsDone () inline static private
References m_IsDone.
Referenced by MissionBase::TickScheduler().
IsRunning()
static bool IsRunning () inline static private
References m_IsRunning.
Referenced by MissionBase::TickScheduler().
Start()
static void Start () inline static private
References TestHarness::Begin(), ErrorEx, TestHarness::GetNSuites(), TestHarness::GetSuite(), AutotestConfigHandler::GetSuites(), AutoTestFixture::LogRPT(), m_IsDone, m_IsRunning, and AutoTestFixture::SetWorldName().
Referenced by MissionBase::TickScheduler().
Update()
static void Update (float deltaTime) inline static private
References TestHarness::End(), TestHarness::Finished(), AutoTestFixture::LogRPT(), m_IsDone, m_IsRunning, TestHarness::Report(), TestHarness::Run(), and AutoTestFixture::SaveXMLReport().
Referenced by MissionBase::TickScheduler().
Field Documentation
m_IsDone
private bool m_IsDone static private
Referenced by IsDone(), Start(), and Update().
m_IsRunning
private bool m_IsRunning static private
Referenced by IsRunning(), Start(), and Update().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Autotest/AutotestRunner.c