DayZ Scripts: ScriptConsoleCameraTab Class Reference
ScriptConsoleCameraTab Class Reference
Private Member Functions
void ScriptConsoleCameraTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
protected void ReloadDOFPresetsList ()
protected void UpdateFOV (float value)
protected void UpdateFocusDistance (float value)
protected void UpdateFocusLength (float value)
protected void UpdateFocusLengthNear (float value)
protected void UpdateBlur (float value)
protected void UpdateFocusDepthOffset (float value)
protected void SetDOF ()
protected void ResetDOF ()
protected void UpdateDOFSliders ()
protected void SaveDOFPreset ()
protected void DeleteDOFPreset ()
protected void OnListItemSelected (int row, int column)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnClick (Widget w, int x, int y, int button)
protected void LoadDOFPreset ()
protected void ToggleValueEditMode (bool editBoxMode)
protected void UpdateValuesFromEditMode ()
bool IsValidEditboxValue (string text, float min, float max)
override void Update (float timeslice)
Private Attributes
protected ref ScriptConsoleSelector m_FOVSelector
protected ref ScriptConsoleSelector m_FocusDistanceSelector
protected ref ScriptConsoleSelector m_FocusLengthSelector
protected ref ScriptConsoleSelector m_FocusLengthNearSelector
protected ref ScriptConsoleSelector m_BlurSelector
protected ref ScriptConsoleSelector m_FocusDepthOffsetSelector
protected TextWidget m_FOVValue
protected EditBoxWidget m_FOVEditbox
protected TextWidget m_FocusDistanceValue
protected EditBoxWidget m_FocusDistanceEditbox
protected TextWidget m_FocusLengthValue
protected EditBoxWidget m_FocusLengthEditbox
protected TextWidget m_FocusLengthNearValue
protected EditBoxWidget m_FocusLengthNearEditbox
protected TextWidget m_BlurValue
protected EditBoxWidget m_BlurEditbox
protected TextWidget m_FocusDepthOffsetValue
protected EditBoxWidget m_FocusDepthOffsetEditbox
protected ButtonWidget m_ResetDOFButton
protected EditBoxWidget m_DOFPresetEditbox
protected Widget m_DOFPresetsPanel
protected Widget m_DOFPresetsBtns
protected ButtonWidget m_DOFShowPresetsBtn
protected TextWidget m_DOFShowPresetsBtnLabel
protected ButtonWidget m_DOFSavePrefabBtn
protected ButtonWidget m_DOFDeletePrefabBtn
protected ButtonWidget m_DOFLoadPrefabBtn
protected FreeDebugCamera m_FreeDebugCamera
protected bool m_MouseMovementEnabled
protected bool m_DOFPresetsVisible
protected bool m_IsCTRLPressed
protected bool m_IsCAPSPressed
protected bool m_IsReturnPressed
protected bool m_ValueEditboxMode
protected float m_ValueEditModeTime
protected bool m_FirstInit
protected ScriptConsoleCameraDOFPreset m_SelectedDOFPreset
protected ref ScriptConsolePresetsList m_DOFPresetsList
protected bool m_CanUseMovement
Constructor & Destructor Documentation
ScriptConsoleCameraTab()
void ScriptConsoleCameraTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline private
References GetScriptConsoleValues(), m_BlurEditbox, m_BlurSelector, m_BlurValue, m_DOFDeletePrefabBtn, m_DOFLoadPrefabBtn, m_DOFPresetEditbox, m_DOFPresetsBtns, m_DOFPresetsList, m_DOFPresetsPanel, m_DOFSavePrefabBtn, m_DOFShowPresetsBtn, m_DOFShowPresetsBtnLabel, m_FirstInit, m_FocusDepthOffsetEditbox, m_FocusDepthOffsetSelector, m_FocusDepthOffsetValue, m_FocusDistanceEditbox, m_FocusDistanceSelector, m_FocusDistanceValue, m_FocusLengthEditbox, m_FocusLengthNearEditbox, m_FocusLengthNearSelector, m_FocusLengthNearValue, m_FocusLengthSelector, m_FocusLengthValue, m_FOVEditbox, m_FOVSelector, m_FOVValue, m_FreeDebugCamera, m_ResetDOFButton, OnListItemSelected(), ReloadDOFPresetsList(), ResetDOF(), UpdateBlur(), UpdateFocusDepthOffset(), UpdateFocusDistance(), UpdateFocusLength(), UpdateFocusLengthNear(), and UpdateFOV().
Member Function Documentation
DeleteDOFPreset()
protected void DeleteDOFPreset () inline private
References ScriptConsoleTabBase::m_ConfigDebugProfile, m_SelectedDOFPreset, ScriptConsoleCameraDOFPreset::Name, and ReloadDOFPresetsList().
Referenced by OnClick().
IsValidEditboxValue()
bool IsValidEditboxValue (string text, float min, float max) inline private
References string::Get(), string::Length(), and string::ToFloat().
Referenced by UpdateValuesFromEditMode().
LoadDOFPreset()
protected void LoadDOFPreset () inline private
References ScriptConsoleCameraDOFPreset::Blur, ScriptConsoleCameraDOFPreset::FocusDepthOffset, ScriptConsoleCameraDOFPreset::FocusDistance, ScriptConsoleCameraDOFPreset::FocusLength, ScriptConsoleCameraDOFPreset::FocusLengthNear, GetScriptConsoleValues(), ScriptConsoleCameraValues::m_CurrentBlur, ScriptConsoleCameraValues::m_CurrentFocusDepthOffset, ScriptConsoleCameraValues::m_CurrentFocusDistance, ScriptConsoleCameraValues::m_CurrentFocusLength, ScriptConsoleCameraValues::m_CurrentFocusLengthNear, m_SelectedDOFPreset, SetDOF(), and UpdateDOFSliders().
Referenced by OnClick().
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References DeleteDOFPreset(), LoadDOFPreset(), m_DOFDeletePrefabBtn, m_DOFLoadPrefabBtn, m_DOFPresetsBtns, m_DOFPresetsPanel, m_DOFPresetsVisible, m_DOFSavePrefabBtn, m_DOFShowPresetsBtn, m_DOFShowPresetsBtnLabel, m_ResetDOFButton, ResetDOF(), and SaveDOFPreset().
OnListItemSelected()
protected void OnListItemSelected (int row, int column) inline private
References ScriptConsoleTabBase::m_ConfigDebugProfile, and m_SelectedDOFPreset.
Referenced by ScriptConsoleCameraTab().
OnMouseEnter()
override bool OnMouseEnter (Widget w, int x, int y) inline private
References Mission::AddActiveInputExcludes(), GetGame(), CGame::GetMission(), and m_DOFPresetEditbox.
OnMouseLeave()
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
References GetFocus(), GetGame(), CGame::GetMission(), m_DOFPresetEditbox, Mission::RemoveActiveInputExcludes(), and SetFocus().
ReloadDOFPresetsList()
protected void ReloadDOFPresetsList () inline private
References Count, ErrorEx, ScriptConsoleTabBase::m_ConfigDebugProfile, m_DOFPresetsList, and ScriptConsoleCameraDOFPreset::Name.
Referenced by DeleteDOFPreset(), SaveDOFPreset(), and ScriptConsoleCameraTab().
ResetDOF()
protected void ResetDOF () inline private
References GetGame(), GetScriptConsoleValues(), CGame::OverrideDOF(), ScriptConsoleCameraValues::SetDefaultValues(), and UpdateDOFSliders().
Referenced by OnClick(), and ScriptConsoleCameraTab().
SaveDOFPreset()
protected void SaveDOFPreset () inline private
References GetScriptConsoleValues(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_DOFPresetEditbox, and ReloadDOFPresetsList().
Referenced by OnClick().
SetDOF()
protected void SetDOF () inline private
References GetGame(), GetScriptConsoleValues(), and CGame::OverrideDOF().
Referenced by LoadDOFPreset(), UpdateBlur(), UpdateFocusDepthOffset(), UpdateFocusDistance(), UpdateFocusLength(), UpdateFocusLengthNear(), and UpdateValuesFromEditMode().
ToggleValueEditMode()
protected void ToggleValueEditMode (bool editBoxMode) inline private
References ScriptConsoleSelector::GetLayoutRoot(), GetScriptConsoleValues(), m_BlurEditbox, m_BlurSelector, m_BlurValue, m_FocusDepthOffsetEditbox, m_FocusDepthOffsetSelector, m_FocusDepthOffsetValue, m_FocusDistanceEditbox, m_FocusDistanceSelector, m_FocusDistanceValue, m_FocusLengthEditbox, m_FocusLengthNearEditbox, m_FocusLengthNearSelector, m_FocusLengthNearValue, m_FocusLengthSelector, m_FocusLengthValue, m_FOVEditbox, m_FOVSelector, and m_FOVValue.
Referenced by Update().
Update()
override void Update (float timeslice) inline private
References Mission::AddActiveInputExcludes(), GetFocus(), GetGame(), CGame::GetMission(), CGame::GetUIManager(), GetWidgetUnderCursor(), KeyState(), m_CanUseMovement, m_DOFPresetEditbox, m_IsCAPSPressed, m_IsCTRLPressed, m_IsReturnPressed, m_MouseMovementEnabled, m_ValueEditboxMode, m_ValueEditModeTime, Mission::RemoveActiveInputExcludes(), UIManager::ShowUICursor(), ToggleValueEditMode(), and UpdateValuesFromEditMode().
UpdateBlur()
protected void UpdateBlur (float value) inline private
References GetScriptConsoleValues(), m_BlurEditbox, m_BlurValue, ScriptConsoleCameraValues::m_CurrentBlur, SetDOF(), and float::ToString().
Referenced by ScriptConsoleCameraTab(), and UpdateValuesFromEditMode().
UpdateDOFSliders()
protected void UpdateDOFSliders () inline private
References GetScriptConsoleValues(), m_BlurEditbox, m_BlurSelector, m_BlurValue, m_FocusDepthOffsetEditbox, m_FocusDepthOffsetSelector, m_FocusDepthOffsetValue, m_FocusDistanceEditbox, m_FocusDistanceSelector, m_FocusDistanceValue, m_FocusLengthEditbox, m_FocusLengthNearEditbox, m_FocusLengthNearSelector, m_FocusLengthNearValue, m_FocusLengthSelector, and m_FocusLengthValue.
Referenced by LoadDOFPreset(), ResetDOF(), and UpdateValuesFromEditMode().
UpdateFocusDepthOffset()
protected void UpdateFocusDepthOffset (float value) inline private
References GetScriptConsoleValues(), ScriptConsoleCameraValues::m_CurrentFocusDepthOffset, m_FocusDepthOffsetEditbox, m_FocusDepthOffsetValue, SetDOF(), and float::ToString().
Referenced by ScriptConsoleCameraTab(), and UpdateValuesFromEditMode().
UpdateFocusDistance()
protected void UpdateFocusDistance (float value) inline private
References GetScriptConsoleValues(), ScriptConsoleCameraValues::m_CurrentFocusDistance, m_FocusDistanceEditbox, m_FocusDistanceValue, SetDOF(), and float::ToString().
Referenced by ScriptConsoleCameraTab(), and UpdateValuesFromEditMode().
UpdateFocusLength()
protected void UpdateFocusLength (float value) inline private
References GetScriptConsoleValues(), ScriptConsoleCameraValues::m_CurrentFocusLength, m_FocusLengthEditbox, m_FocusLengthValue, SetDOF(), and float::ToString().
Referenced by ScriptConsoleCameraTab(), and UpdateValuesFromEditMode().
UpdateFocusLengthNear()
protected void UpdateFocusLengthNear (float value) inline private
References GetScriptConsoleValues(), ScriptConsoleCameraValues::m_CurrentFocusLengthNear, m_FocusLengthNearEditbox, m_FocusLengthNearValue, SetDOF(), and float::ToString().
Referenced by ScriptConsoleCameraTab(), and UpdateValuesFromEditMode().
UpdateFOV()
protected void UpdateFOV (float value) inline private
References GetScriptConsoleValues(), ScriptConsoleCameraValues::m_CurrentFOV, m_FOVEditbox, m_FOVValue, m_FreeDebugCamera, and float::ToString().
Referenced by ScriptConsoleCameraTab(), and UpdateValuesFromEditMode().
UpdateValuesFromEditMode()
protected void UpdateValuesFromEditMode () inline private
References IsValidEditboxValue(), m_BlurEditbox, m_FocusDepthOffsetEditbox, m_FocusDistanceEditbox, m_FocusLengthEditbox, m_FocusLengthNearEditbox, m_FOVEditbox, SetDOF(), UpdateBlur(), UpdateDOFSliders(), UpdateFocusDepthOffset(), UpdateFocusDistance(), UpdateFocusLength(), UpdateFocusLengthNear(), and UpdateFOV().
Referenced by Update().
Field Documentation
m_BlurEditbox
protected EditBoxWidget m_BlurEditbox private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateBlur(), UpdateDOFSliders(), and UpdateValuesFromEditMode().
m_BlurSelector
protected ref ScriptConsoleSelector m_BlurSelector private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), and UpdateDOFSliders().
m_BlurValue
protected TextWidget m_BlurValue private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateBlur(), and UpdateDOFSliders().
m_CanUseMovement
protected bool m_CanUseMovement private
Referenced by Update().
m_DOFDeletePrefabBtn
protected ButtonWidget m_DOFDeletePrefabBtn private
Referenced by OnClick(), and ScriptConsoleCameraTab().
m_DOFLoadPrefabBtn
protected ButtonWidget m_DOFLoadPrefabBtn private
Referenced by OnClick(), and ScriptConsoleCameraTab().
m_DOFPresetEditbox
protected EditBoxWidget m_DOFPresetEditbox private
Referenced by OnMouseEnter(), OnMouseLeave(), SaveDOFPreset(), ScriptConsoleCameraTab(), and Update().
m_DOFPresetsBtns
protected Widget m_DOFPresetsBtns private
Referenced by OnClick(), and ScriptConsoleCameraTab().
m_DOFPresetsList
protected ref ScriptConsolePresetsList m_DOFPresetsList private
Referenced by ReloadDOFPresetsList(), and ScriptConsoleCameraTab().
m_DOFPresetsPanel
protected Widget m_DOFPresetsPanel private
Referenced by OnClick(), and ScriptConsoleCameraTab().
m_DOFPresetsVisible
protected bool m_DOFPresetsVisible private
Referenced by OnClick().
m_DOFSavePrefabBtn
protected ButtonWidget m_DOFSavePrefabBtn private
Referenced by OnClick(), and ScriptConsoleCameraTab().
m_DOFShowPresetsBtn
protected ButtonWidget m_DOFShowPresetsBtn private
Referenced by OnClick(), and ScriptConsoleCameraTab().
m_DOFShowPresetsBtnLabel
protected TextWidget m_DOFShowPresetsBtnLabel private
Referenced by OnClick(), and ScriptConsoleCameraTab().
m_FirstInit
protected bool m_FirstInit private
Referenced by ScriptConsoleCameraTab().
m_FocusDepthOffsetEditbox
protected EditBoxWidget m_FocusDepthOffsetEditbox private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateDOFSliders(), UpdateFocusDepthOffset(), and UpdateValuesFromEditMode().
m_FocusDepthOffsetSelector
protected ref ScriptConsoleSelector m_FocusDepthOffsetSelector private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), and UpdateDOFSliders().
m_FocusDepthOffsetValue
protected TextWidget m_FocusDepthOffsetValue private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateDOFSliders(), and UpdateFocusDepthOffset().
m_FocusDistanceEditbox
protected EditBoxWidget m_FocusDistanceEditbox private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateDOFSliders(), UpdateFocusDistance(), and UpdateValuesFromEditMode().
m_FocusDistanceSelector
protected ref ScriptConsoleSelector m_FocusDistanceSelector private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), and UpdateDOFSliders().
m_FocusDistanceValue
protected TextWidget m_FocusDistanceValue private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateDOFSliders(), and UpdateFocusDistance().
m_FocusLengthEditbox
protected EditBoxWidget m_FocusLengthEditbox private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateDOFSliders(), UpdateFocusLength(), and UpdateValuesFromEditMode().
m_FocusLengthNearEditbox
protected EditBoxWidget m_FocusLengthNearEditbox private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateDOFSliders(), UpdateFocusLengthNear(), and UpdateValuesFromEditMode().
m_FocusLengthNearSelector
protected ref ScriptConsoleSelector m_FocusLengthNearSelector private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), and UpdateDOFSliders().
m_FocusLengthNearValue
protected TextWidget m_FocusLengthNearValue private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateDOFSliders(), and UpdateFocusLengthNear().
m_FocusLengthSelector
protected ref ScriptConsoleSelector m_FocusLengthSelector private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), and UpdateDOFSliders().
m_FocusLengthValue
protected TextWidget m_FocusLengthValue private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateDOFSliders(), and UpdateFocusLength().
m_FOVEditbox
protected EditBoxWidget m_FOVEditbox private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), UpdateFOV(), and UpdateValuesFromEditMode().
m_FOVSelector
protected ref ScriptConsoleSelector m_FOVSelector private
Referenced by ScriptConsoleCameraTab(), and ToggleValueEditMode().
m_FOVValue
protected TextWidget m_FOVValue private
Referenced by ScriptConsoleCameraTab(), ToggleValueEditMode(), and UpdateFOV().
m_FreeDebugCamera
protected FreeDebugCamera m_FreeDebugCamera private
Referenced by ScriptConsoleCameraTab(), and UpdateFOV().
m_IsCAPSPressed
protected bool m_IsCAPSPressed private
Referenced by Update().
m_IsCTRLPressed
protected bool m_IsCTRLPressed private
Referenced by Update().
m_IsReturnPressed
protected bool m_IsReturnPressed private
Referenced by Update().
m_MouseMovementEnabled
protected bool m_MouseMovementEnabled private
Referenced by Update().
m_ResetDOFButton
protected ButtonWidget m_ResetDOFButton private
Referenced by OnClick(), and ScriptConsoleCameraTab().
m_SelectedDOFPreset
protected ScriptConsoleCameraDOFPreset m_SelectedDOFPreset private
Referenced by DeleteDOFPreset(), LoadDOFPreset(), and OnListItemSelected().
m_ValueEditboxMode
protected bool m_ValueEditboxMode private
Referenced by Update().
m_ValueEditModeTime
protected float m_ValueEditModeTime private
Referenced by Update().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptConsoleCameraTab.c