DayZ Scripts: AmmoTypesAPI Class Reference
AmmoTypesAPI Class Reference
Private Member Functions
private void AmmoTypesAPI ()
private void ~AmmoTypesAPI ()
Static Private Member Functions
static proto bool Exists (string ammoType)
Check if ammoType exists (registered in cfgAmmoTypes)
static proto bool GetAmmoType (string magazineType, out string ammoType)
Get the default ammoType of a magazine.
static bool MagazineTypeToAmmoType (string magazineType, out string ammoType)
Helper method.
static void Init ()
static void AddExplosionParticleEffect (string ammoName, string surfaceName, int particleID)
static int GetExplosionParticleID (string ammoName, string surfaceName)
static void Cleanup ()
Static Private Attributes
static protected ref map< string, ref map< string, int > > m_TypeToSurfaceParticleIDMap
Constructor & Destructor Documentation
AmmoTypesAPI()
private void AmmoTypesAPI () inline private
~AmmoTypesAPI()
private void ~AmmoTypesAPI () inline private
Member Function Documentation
AddExplosionParticleEffect()
static void AddExplosionParticleEffect (string ammoName, string surfaceName, int particleID) inline static private
References m_TypeToSurfaceParticleIDMap.
Referenced by Init().
Cleanup()
static void Cleanup () inline static private
References m_TypeToSurfaceParticleIDMap.
Referenced by MissionBaseWorld::~MissionBase().
Exists()
static proto bool Exists (string ammoType) static private
Check if ammoType exists (registered in cfgAmmoTypes)
Referenced by MagazineTypeToAmmoType().
GetAmmoType()
static proto bool GetAmmoType (string magazineType, out string ammoType) static private
Get the default ammoType of a magazine.
Referenced by MagazineTypeToAmmoType().
GetExplosionParticleID()
static int GetExplosionParticleID (string ammoName, string surfaceName) inline static private
References m_TypeToSurfaceParticleIDMap.
Referenced by CGame::ExplosionEffects().
Init()
static void Init () inline static private
References AddExplosionParticleEffect(), ParticleList::EXPLOSION_GRENADE_ICE, ParticleList::EXPLOSION_GRENADE_SNOW, ParticleList::EXPLOSION_LANDMINE, and m_TypeToSurfaceParticleIDMap.
Referenced by MissionBaseWorld::MissionBase().
MagazineTypeToAmmoType()
static bool MagazineTypeToAmmoType (string magazineType, out string ammoType) inline static private
Helper method.
References ErrorEx, Exists(), and GetAmmoType().
Referenced by Weapon::FillChamber(), Weapon::FillInnerMagazine(), and Weapon::FillSpecificChamber().
Field Documentation
m_TypeToSurfaceParticleIDMap
protected ref map<string, ref map<string, int> > m_TypeToSurfaceParticleIDMap static private
Referenced by AddExplosionParticleEffect(), Cleanup(), GetExplosionParticleID(), and Init().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Global/AmmoTypes.c