DayZ Scripts: P:/scripts/5_Mission/mission/MissionBenchmark.c File Reference
MissionBenchmark.c File Reference
Data Structures
class BenchmarkLocation
class MissionBenchmark
Functions
void AddLocation (notnull BenchmarkLocation loc)
void AddQuickLocation (string name, vector pos, vector lookAtPos)
void AddTeleport ()
void AddWait ()
void LogToRPT (bool logRPT)
void DoDevPrints (bool doPrints)
void SetPreloadLengthTime (int seconds)
void SetTestTimeMultiplier (float multiplier)
void SetCSVName (string name)
Variables
class BenchmarkLocation m_LogToRPT
bool m_DoDevPrints
int m_PreloadLength = 5
float m_TimeMultiplier = 1
string m_CSVName
ref array< ref BenchmarkLocation > m_Locations = new array<ref BenchmarkLocation>()
Function Documentation
AddLocation()
void AddLocation (notnull BenchmarkLocation loc)
References m_Locations.
AddQuickLocation()
void AddQuickLocation (string name, vector pos, vector lookAtPos)
References m_Locations, name, BenchmarkLocation::SetLookAtPosition(), and BenchmarkLocation::SetPosition().
AddTeleport()
void AddTeleport ()
References m_Locations, and BenchmarkLocation::SetDummyTeleport().
AddWait()
void AddWait ()
References m_Locations, and BenchmarkLocation::SetDummyWait().
DoDevPrints()
void DoDevPrints (bool doPrints)
References m_DoDevPrints.
LogToRPT()
void LogToRPT (bool logRPT)
References m_LogToRPT.
SetCSVName()
void SetCSVName (string name)
References m_CSVName, and name.
SetPreloadLengthTime()
void SetPreloadLengthTime (int seconds)
References m_PreloadLength.
SetTestTimeMultiplier()
void SetTestTimeMultiplier (float multiplier)
References m_TimeMultiplier.
Variable Documentation
m_CSVName
string m_CSVName
Referenced by SetCSVName().
m_DoDevPrints
bool m_DoDevPrints
Referenced by DoDevPrints().
m_Locations
ref array<ref BenchmarkLocation> m_Locations = new array<ref BenchmarkLocation>()
Referenced by AddLocation(), AddQuickLocation(), AddTeleport(), and AddWait().
m_LogToRPT
class BenchmarkLocation m_LogToRPT
Referenced by LogToRPT().
m_PreloadLength
int m_PreloadLength = 5
Referenced by SetPreloadLengthTime().
m_TimeMultiplier
float m_TimeMultiplier = 1
Referenced by SetTestTimeMultiplier().