DayZ Scripts: AutoTestFixture Class Reference
AutoTestFixture Class Reference
Static Private Member Functions
static bool SaveXMLReport (string data, out string errorMessage)
static EntityAI SpawnEntityAI (string typeName, int flags=ECE_PLACE_ON_SURFACE)
static void SetWorldName ()
static string GetWorldName ()
static void LogRPT (string message)
Static Private Attributes
static private const string REPORT_FILE_NAME_TEMPLATE = "$mission:Autotest_%1.xml"
static private const string DATETIME_FORMAT = "%1%2%3T%4%5%6Z"
static private string m_WorldName
Member Function Documentation
GetWorldName()
static string GetWorldName () inline static private
References m_WorldName.
LogRPT()
static void LogRPT (string message) inline static private
References PrintToRPT().
Referenced by CGame::AutoTestLaunch(), AutotestConfigHandler::LoadData(), AutotestRunner::Start(), and AutotestRunner::Update().
SaveXMLReport()
static bool SaveXMLReport (string data, out string errorMessage) inline static private
References CloseFile(), DATETIME_FORMAT, FPrint(), GetHourMinuteSecondUTC(), GetYearMonthDayUTC(), OpenFile(), and REPORT_FILE_NAME_TEMPLATE.
Referenced by AutotestRunner::Update().
SetWorldName()
static void SetWorldName () inline static private
References GetGame(), CGame::GetWorldName(), m_WorldName, and string::ToLower().
Referenced by AutotestRunner::Start().
SpawnEntityAI()
static EntityAI SpawnEntityAI (string typeName, int flags = ECE_PLACE_ON_SURFACE) inline static private
References ECE_PLACE_ON_SURFACE, and g_Game.
Field Documentation
DATETIME_FORMAT
private const string DATETIME_FORMAT = "%1%2%3T%4%5%6Z" static private
Referenced by SaveXMLReport().
m_WorldName
private string m_WorldName static private
Referenced by GetWorldName(), and SetWorldName().
REPORT_FILE_NAME_TEMPLATE
private const string REPORT_FILE_NAME_TEMPLATE = "$mission:Autotest_%1.xml" static private
Referenced by SaveXMLReport().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Autotest/AutoTestFixture.c