DayZ Scripts: P:/scripts/4_World/Classes/PlayerSymptoms/States/Primary/FreezeState.c File Reference
FreezeState.c File Reference
Data Structures
class SymptomBase
Functions
class FreezeSymptom extends SymptomBase OnInit ()
Callback for user defined initialization. Called for all suites during TestHarness.Begin().
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnAnimationPlayFailed ()
override bool CanActivate ()
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override SmptAnimMetaBase SpawnAnimMetaObject ()
Function Documentation
CanActivate()
override bool CanActivate ()
Referenced by SymptomManager::UpdateActiveSymptoms().
OnAnimationPlayFailed()
override void OnAnimationPlayFailed ()
OnGetActivatedClient()
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
OnGetActivatedServer()
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
OnGetDeactivatedClient()
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
OnGetDeactivatedServer()
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
OnUpdateClient()
override void OnUpdateClient (PlayerBase player, float deltatime)
References LogManager::IsSymptomLogEnable(), m_Player, PlaySound(), Debug::SymptomLog(), and ToString().
OnUpdateServer()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
SpawnAnimMetaObject()
override SmptAnimMetaBase SpawnAnimMetaObject ()
Referenced by SymptomManager::SetAnimation().