DayZ Scripts: P:/scripts/4_World/Entities/ScriptedLightBase/Dimming/LightDimming.c File Reference
LightDimming.c File Reference
Enumerations
enum ELightDimmingState { PAUSED , DIMMING , PAUSED_DIMMED , BRIGHTENING }
Functions
void LightDimming (ScriptedLightBase light, float baseBrightness, DimmingConfig dimCfg)
ELightDimmingState GetState ()
returns one of STATE_...
void AddConfig (DimmingConfig cfg)
protected void SetDimmingVal (float val)
protected void AdvanceState (ELightDimmingState lastState)
protected void SelectPattern ()
void SwapConfig (int index)
void HandleDimming (float timeSlice)
Variables
enum ELightDimmingState FLICKER_TIME = 0.05
protected float m_DimBrigthnessBase
protected float m_DimBrigthnessSpeedCoef
protected float m_DimBrigthnessTarget
protected float m_DimDelta
protected int m_CurrentPatternID
protected int m_CurrentEntryID
protected bool m_ToBeDestroyed
protected ELightDimmingState m_DimState
protected ScriptedLightBase m_Light
protected DimmingConfig m_ActiveCfg
protected ref array< ref DimmingConfig > m_Configs = new array<ref DimmingConfig>()
Enumeration Type Documentation
ELightDimmingState
enum ELightDimmingState
Enumerator
PAUSED
DIMMING
PAUSED_DIMMED
BRIGHTENING
Function Documentation
AddConfig()
void AddConfig (DimmingConfig cfg)
References m_Configs.
AdvanceState()
protected void AdvanceState (ELightDimmingState lastState)
References AdvanceState(), FLICKER_TIME, m_ActiveCfg, DimmingConfig::m_BrightenSpeedMax, DimmingConfig::m_BrightenSpeedMin, DimmingConfig::m_BrightenSpeedPatterns, DimmingConfig::m_BrightnessPatterns, m_CurrentEntryID, m_CurrentPatternID, m_DimBrigthnessBase, DimmingConfig::m_DimBrigthnessDurationMin, DimmingConfig::m_DimBrigthnessMax, DimmingConfig::m_DimBrigthnessMin, DimmingConfig::m_DimBrigthnessPauseMax, DimmingConfig::m_DimBrigthnessPauseMin, m_DimBrigthnessSpeedCoef, m_DimBrigthnessTarget, m_DimDelta, DimmingConfig::m_DimSpeedMax, DimmingConfig::m_DimSpeedMin, DimmingConfig::m_DimSpeedPatterns, m_DimState, DimmingConfig::m_DurationPatterns, DimmingConfig::m_PausePatterns, m_ToBeDestroyed, DimmingConfig::m_UsePatterns, Math::RandomFloat(), SelectPattern(), and SetDimmingVal().
Referenced by AdvanceState(), and HandleDimming().
GetState()
ELightDimmingState GetState ()
returns one of STATE_...
returns the state of climb (enum value of ClimbStates);
References m_DimState, and m_State.
Referenced by ItemBase::CanAttach(), ItemBase::CanBeManipulated(), ItemBase::CanBePacked(), ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), CanDisplayAttachmentSlot(), FireworksLauncher::CanPutInCargo(), FireworksLauncher::CanPutIntoHands(), CanReceiveAttachment(), ItemBase::EEHealthLevelChanged(), GetStateString(), ItemBase::GetViewIndex(), ItemBase::HandleOpeningsPhysics(), FireworksLauncher::IsIgnited(), IsTakeable(), FireworksLauncher::OnPlacementComplete(), RefreshState(), ActionFishingNewCB::ToggleFishBiting(), ItemBase::UpdatePhysics(), UpdateProxySelections(), and ItemBase::UpdateVisuals().
HandleDimming()
void HandleDimming (float timeSlice)
References AdvanceState(), Math::Lerp(), m_DimBrigthnessBase, m_DimBrigthnessSpeedCoef, m_DimBrigthnessTarget, m_DimDelta, m_DimState, m_ToBeDestroyed, and SetDimmingVal().
LightDimming()
void LightDimming (ScriptedLightBase light, float baseBrightness, DimmingConfig dimCfg)
References m_ActiveCfg, m_Configs, m_DimBrigthnessBase, and m_Light.
Referenced by EntityLightSource::EnableDimming().
SelectPattern()
protected void SelectPattern ()
References m_ActiveCfg, DimmingConfig::m_BrightnessPatterns, m_CurrentEntryID, m_CurrentPatternID, m_Light, DimmingConfig::m_PatternCount, DimmingConfig::m_PatternRepeatCount, and m_ToBeDestroyed.
Referenced by AdvanceState().
SetDimmingVal()
protected void SetDimmingVal (float val)
References m_Light.
Referenced by AdvanceState(), and HandleDimming().
SwapConfig()
void SwapConfig (int index)
References m_ActiveCfg, m_Configs, m_CurrentEntryID, m_CurrentPatternID, and m_DimState.
Variable Documentation
FLICKER_TIME
enum ELightDimmingState FLICKER_TIME = 0.05
Referenced by AdvanceState().
m_ActiveCfg
protected DimmingConfig m_ActiveCfg
Referenced by AdvanceState(), LightDimming(), SelectPattern(), and SwapConfig().
m_Configs
protected ref array<ref DimmingConfig> m_Configs = new array<ref DimmingConfig>()
Referenced by AddConfig(), LightDimming(), and SwapConfig().
m_CurrentEntryID
protected int m_CurrentEntryID
Referenced by AdvanceState(), SelectPattern(), and SwapConfig().
m_CurrentPatternID
protected int m_CurrentPatternID
Referenced by AdvanceState(), SelectPattern(), and SwapConfig().
m_DimBrigthnessBase
protected float m_DimBrigthnessBase
Referenced by AdvanceState(), HandleDimming(), and LightDimming().
m_DimBrigthnessSpeedCoef
protected float m_DimBrigthnessSpeedCoef
Referenced by AdvanceState(), and HandleDimming().
m_DimBrigthnessTarget
protected float m_DimBrigthnessTarget
Referenced by AdvanceState(), and HandleDimming().
m_DimDelta
protected float m_DimDelta
Referenced by AdvanceState(), and HandleDimming().
m_DimState
protected ELightDimmingState m_DimState
Referenced by AdvanceState(), GetState(), HandleDimming(), and SwapConfig().
m_Light
protected ScriptedLightBase m_Light
m_ToBeDestroyed
protected bool m_ToBeDestroyed
Referenced by AdvanceState(), HandleDimming(), and SelectPattern().