DayZ Scripts: P:/scripts/4_World/Classes/ContaminatedArea/ContaminatedArea_Dynamic.c File Reference
ContaminatedArea_Dynamic.c File Reference
Data Structures
class ShellLight
Functions
override void EEOnCECreate ()
override void OnVariablesSynchronized ()
override void Tick ()
override void SetupZoneData (EffectAreaParams params)
override void DeferredInit ()
override void InitZoneServer ()
void SpawnItems ()
override void CreateTrigger (vector pos, int radius)
void PlayFX ()
void PlayExplosionLight ()
void PlayFlareVFX ()
Variables
ShellLight m_OffsetPos
protected ref Timer m_StartupTimer
protected ref Timer m_FXTimer
protected FlareLight m_FlareLight
protected ShellLight m_ShellLight
const int AIRBORNE_EXPLOSION_DELAY = 20
const int AREA_SETUP_DELAY = 10
const float AIRBORNE_FX_OFFSET = 50
const float ARTILLERY_SHELL_SPEED = 100
const ref array< string > SPAWN_ITEM_TYPE = {"Grenade_ChemGas"}
const ref array< int > SPAWN_ITEM_COUNT = {Math.RandomIntInclusive(2,5)}
const ref array< float > SPAWN_ITEM_RAD_MIN = {5}
const ref array< float > SPAWN_ITEM_RAD_MAX = {15}
Function Documentation
CreateTrigger()
override void CreateTrigger (vector pos, int radius)
References ContaminatedTrigger_Dynamic(), and m_DecayState.
DeferredInit()
override void DeferredInit ()
References AIRBORNE_FX_OFFSET, GetPosition, InitZone(), m_DecayState, m_OffsetPos, m_Position, PlayFlareVFX(), and SetupZoneData().
EEOnCECreate()
override void EEOnCECreate ()
References AIRBORNE_EXPLOSION_DELAY, AIRBORNE_FX_OFFSET, AREA_SETUP_DELAY, ARTILLERY_SHELL_SPEED, CALL_CATEGORY_GAMEPLAY, vector::Distance(), vector::DistanceSq(), WorldData::GetArtyFiringPos(), GetGame(), CGame::GetMission(), GetPosition, Mission::GetWorldData(), m_DecayState, m_FXTimer, m_OffsetPos, m_StartupTimer, and CGame::RPC().
InitZoneServer()
override void InitZoneServer ()
References SpawnItems().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
References m_DecayState, and PlayExplosionLight().
Referenced by Process().
PlayExplosionLight()
void PlayExplosionLight ()
References m_OffsetPos, and m_ShellLight.
Referenced by OnVariablesSynchronized().
PlayFlareVFX()
void PlayFlareVFX ()
References ECE_LOCAL, ECE_SETUP, GetGame(), m_FlareLight, and m_OffsetPos.
Referenced by DeferredInit().
PlayFX()
void PlayFX ()
References GetGame(), m_OffsetPos, CGame::RPC(), SetDecayState(), and vector::Zero.
SetupZoneData()
override void SetupZoneData (EffectAreaParams params)
References ParticleList::CONTAMINATED_AREA_GAS_AROUND, ParticleList::CONTAMINATED_AREA_GAS_BIGASS, ParticleList::CONTAMINATED_AREA_GAS_TINY, m_Position, and vector::ToString().
Referenced by DeferredInit().
SpawnItems()
void SpawnItems ()
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), m_Position, Math3D::MatrixIdentity4(), vector::RandomDir2D(), Math::RandomFloatInclusive(), SPAWN_ITEM_COUNT, SPAWN_ITEM_RAD_MAX, SPAWN_ITEM_RAD_MIN, and SPAWN_ITEM_TYPE.
Referenced by InitZoneServer(), OnFinishProgressServer(), and PerformRecipe().
Tick()
override void Tick ()
References GetFinishDecayLifetime(), GetRemainingTime(), GetStartDecayLifetime(), and SetDecayState().
Variable Documentation
AIRBORNE_EXPLOSION_DELAY
const int AIRBORNE_EXPLOSION_DELAY = 20
Referenced by EEOnCECreate().
AIRBORNE_FX_OFFSET
const float AIRBORNE_FX_OFFSET = 50
Referenced by DeferredInit(), and EEOnCECreate().
AREA_SETUP_DELAY
const int AREA_SETUP_DELAY = 10
Referenced by EEOnCECreate().
ARTILLERY_SHELL_SPEED
const float ARTILLERY_SHELL_SPEED = 100
Referenced by EEOnCECreate().
m_FlareLight
protected FlareLight m_FlareLight
Referenced by PlayFlareVFX().
m_FXTimer
protected ref Timer m_FXTimer
Referenced by EEOnCECreate().
m_OffsetPos
ShellLight m_OffsetPos
Referenced by DeferredInit(), EEOnCECreate(), PlayExplosionLight(), PlayFlareVFX(), and PlayFX().
m_ShellLight
protected ShellLight m_ShellLight
Referenced by PlayExplosionLight().
m_StartupTimer
protected ref Timer m_StartupTimer
Referenced by EEOnCECreate().
SPAWN_ITEM_COUNT
const ref array<int> SPAWN_ITEM_COUNT = {Math.RandomIntInclusive(2,5)}
Referenced by SpawnItems().
SPAWN_ITEM_RAD_MAX
const ref array<float> SPAWN_ITEM_RAD_MAX = {15}
Referenced by SpawnItems().
SPAWN_ITEM_RAD_MIN
const ref array<float> SPAWN_ITEM_RAD_MIN = {5}
Referenced by SpawnItems().
SPAWN_ITEM_TYPE
const ref array<string> SPAWN_ITEM_TYPE = {"Grenade_ChemGas"}
Referenced by SpawnItems().