DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/ActionTargets.c File Reference
ActionTargets.c File Reference
Data Structures
class VicinityObjects
objects in vicinity - extended with secondary object which is parent of that Object
class ActionTargets
class ObjectGroup
Functions
void ActionTarget (Object object, Object parent, int componentIndex, vector cursorHitPos, float utility, string surfaceName="")
Object GetObject ()
Object GetParent ()
Get parent of the Effect.
bool IsProxy ()
int GetComponentIndex ()
float GetUtility ()
vector GetCursorHitPos ()
void SetCursorHitPos (vector cursor_position)
string GetSurfaceName ()
int GetSurfaceLiquidType ()
void DbgPrintTargetDump ()
string DumpToString ()
Variables
class VicinityObjects m_Object
private Object m_Parent
private int m_ComponentIndex
private vector m_CursorHitPos
private float m_Utility
private string m_SurfaceName
private int m_SurfaceLiquidType = LIQUID_NONE
Function Documentation
ActionTarget()
void ActionTarget (Object object, Object parent, int componentIndex, vector cursorHitPos, float utility, string surfaceName = "")
References ActionTarget(), SurfaceInfo::GetByFile(), SurfaceInfo::GetLiquidType(), LIQUID_NONE, m_ComponentIndex, m_CursorHitPos, m_Object, m_Parent, m_SurfaceLiquidType, m_SurfaceName, and m_Utility.
Referenced by ActionTarget(), ActionManagerClient::CanPerformActionFromInventory(), ActionManagerClient::CanPerformActionFromQuickbar(), ActionManagerClient::CanSetActionFromInventory(), FindActionTarget(), ActionManagerClient::FindActionTarget(), ActionManagerClient::FindContextualUserActions(), ActionManagerClient::ForceTarget(), GetSelectedLightSourceTarget(), ActionBaseCB::GetTarget(), ActionTargets::GetTarget(), ActionInput::GetUsedActionTarget(), UIScriptedMenu::HandleLights(), UIScriptedMenu::HandleNVG(), ActionBase::HandleReciveData(), ActionWorldCraft::HandleReciveData(), FirearmActionAttachMagazine::HandleReciveData(), FirearmActionAttachMagazineQuick::HandleReciveData(), OnCenterPanelDropReceived(), BotWaitForChangeInHands::OnEntry(), ActionManagerClient::PerformActionFromInventory(), ActionManagerClient::PerformActionFromQuickbar(), ManBase::PhysicalPredictiveDropItem(), FirearmActionAttachMagazineQuick::Post_SetupAction(), ManBase::PredictiveForceSwapEntities(), ManBase::PredictiveSwapEntities(), ManBase::PredictiveTakeEntityToHands(), ActionBase::ReadFromContext(), ManBase::ReloadWeapon(), HudDebugWinHorticulture::SendRPCUpdate(), InventoryActionHandler::SetAction(), ActionManagerClient::SetActionFromInventory(), PluginBase::SetDeveloperItemClient(), CAContinuousDisinfectPlant::Setup(), SetupAction(), ActionManagerServer::StartDeliveredAction(), ActionTargets::Update(), ActionManagerServer::Update(), CarHornShortActionInput::UpdatePossibleActions(), ToggleLightsActionInput::UpdatePossibleActions(), and ToggleNVGActionInput::UpdatePossibleActions().
DbgPrintTargetDump()
void DbgPrintTargetDump ()
References DumpToString(), and Print().
DumpToString()
string DumpToString ()
References m_ComponentIndex, m_CursorHitPos, m_Object, m_Parent, m_Utility, vector::ToString(), and float::ToString().
GetComponentIndex()
int GetComponentIndex ()
References m_ComponentIndex.
GetCursorHitPos()
vector GetCursorHitPos ()
References m_CursorHitPos.
GetObject()
Object GetObject ()
References m_Object.
Referenced by Container::CanCombineAmmo(), Particle::CreateParticleEffect(), VicinityObjects::GetRawVicinityObjects(), VicinityObjects::GetVicinityObjects(), Container::IsItemActive(), Container::IsItemWithQuantityActive(), ParticleList::PreloadParticles(), Container::TransferItem(), and Container::TransferItemToVicinity().
GetSurfaceLiquidType()
int GetSurfaceLiquidType ()
References m_SurfaceLiquidType.
Referenced by Can().
GetSurfaceName()
string GetSurfaceName ()
References m_SurfaceName.
GetUtility()
float GetUtility ()
References m_Utility.
IsProxy()
bool IsProxy ()
References m_Parent.
SetCursorHitPos()
void SetCursorHitPos (vector cursor_position)
References m_CursorHitPos.
Variable Documentation
m_ComponentIndex
private int m_ComponentIndex
m_CursorHitPos
private vector m_CursorHitPos
Referenced by ActionTarget(), DumpToString(), GetCursorHitPos(), and SetCursorHitPos().
m_Object
class VicinityObjects m_Object
m_Parent
private Object m_Parent
m_SurfaceLiquidType
private int m_SurfaceLiquidType = LIQUID_NONE
Referenced by ActionTarget(), and GetSurfaceLiquidType().
m_SurfaceName
private string m_SurfaceName
Referenced by ActionTarget(), and GetSurfaceName().
m_Utility
private float m_Utility
Referenced by ActionTarget(), DumpToString(), and GetUtility().