DayZ Scripts: P:/scripts/4_World/Entities/Building/OutdoorThermometer.c File Reference
OutdoorThermometer.c File Reference
Data Structures
class OutdoorThermometerManager
class Land_OutsideThermometer
class Land_OutsideThermometer_2
Functions
void OutdoorThermometer ()
void ~OutdoorThermometer ()
void UpdateTemperature ()
private void LateInit ()
Land_OutsideThermometer OutdoorThermometer Land_OutsideThermometer_1 ()
void Land_OutsideThermometer ()
Variables
class OutdoorThermometerManager m_MaxValue = 50
protected float m_MinValue = -20
Function Documentation
Land_OutsideThermometer()
void Land_OutsideThermometer ()
References m_MaxValue, and m_MinValue.
Land_OutsideThermometer_1()
Land_OutsideThermometer OutdoorThermometer Land_OutsideThermometer_1 ()
References GetGame(), CGame::RegisterNetworkStaticObject(), and UpdateTemperature().
LateInit()
private void LateInit ()
Referenced by Init(), and OutdoorThermometer().
OutdoorThermometer()
void OutdoorThermometer ()
References OutdoorThermometerManager::Add(), CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and LateInit().
UpdateTemperature()
void UpdateTemperature ()
References Math::Clamp(), g_Game, m_MaxValue, and m_MinValue.
Referenced by Land_OutsideThermometer_1().
~OutdoorThermometer()
void ~OutdoorThermometer ()
References OutdoorThermometerManager::Remove().
Variable Documentation
m_MaxValue
class OutdoorThermometerManager m_MaxValue = 50
Referenced by Land_OutsideThermometer::Land_OutsideThermometer(), and Land_OutsideThermometer_2::Land_OutsideThermometer_2().
m_MinValue
protected float m_MinValue = -20
Referenced by Land_OutsideThermometer::Land_OutsideThermometer(), and Land_OutsideThermometer_2::Land_OutsideThermometer_2().