DayZ Scripts: P:/scripts/2_GameLib/tests/TestingFramework.c File Reference
TestingFramework.c File Reference
Data Structures
class Test
Attribute used for tests annotation and assignment to Suites.
class TestHarness
Collection and main interface of the Testing framework.
class TestBase
Test base class.
Functions
void Step (EStage stage=EStage.Main)
TestHarness Managed SetResult (TestResultBase res)
Collection of tests.
proto static native bool Run ()
static proto string Report ()
Generates a xml report.
proto static native int GetNSuites ()
Returns number of test suites.
proto static native TestSuite GetSuite (int handle)
Returns a test suite.
proto static native TestSuite ActiveSuite ()
Returns currently active TestSuite or null when none is active.
proto static native bool Finished ()
Returns true when all tests and suites finished.
proto static native void Begin ()
Starts up the testing process and initializes the structures.
proto static native void End ()
Finalizes the testing process.
proto native int GetNTests ()
Returns the number for tests within this suite.
proto native TestBase GetTest (int handle)
Returns a test.
proto native void SetEnabled (bool val)
Enables/Disables the suites. Disabled suites won't run at all.
proto native bool IsEnabled ()
Enabled flag getter.
proto string GetName ()
Suite class name getter. Strictly for UI porposes!
protected void OnInit ()
Callback for user defined initialization. Called for all suites during TestHarness.Begin().
TestBase Managed Failure ()
Return true of the result means failure.
proto native TestResultBase GetResult ()
Result getter.
string FailureText ()
Text used for xml report output.
proto native bool NativeFailure ()
proto native string NativeFailureText ()
Variables
class Test Setup
Stage definition used in conjunction with Step attribute.
class Test Main
class Test Stage
Attribute which marks a method as part of the testing process.
Function Documentation
ActiveSuite()
proto static native TestSuite ActiveSuite () static
Returns currently active TestSuite or null when none is active.
Begin()
proto static native void Begin () static
Starts up the testing process and initializes the structures.
End()
proto static native void End () static
Finalizes the testing process.
Referenced by DeactivateFishing(), ActionBase::Interrupt(), AnimatedActionBase::Interrupt(), FirearmActionDetachMagazine::OnStageStart(), ActionGetInTransport::OnUpdate(), ActionGetOutTransport::OnUpdate(), ActionSwitchSeats::OnUpdate(), FirearmActionBase::OnUpdate(), and Pulling().
Finished()
proto static native bool Finished () static
Returns true when all tests and suites finished.
GetNSuites()
proto static native int GetNSuites () static
Returns number of test suites.
GetResult()
proto native TestResultBase GetResult ()
Result getter.
GetSuite()
proto static native TestSuite GetSuite (int handle) static
Returns a test suite.
Report()
static proto string Report () static
Generates a xml report.
Run()
proto static native bool Run () static
Starts the testing process. Returns true when all tests have finished. If some of them are still in progress false is reported.
References MissionBatPath.