DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/TargetConditionsComponents/CCTWaterSurface.c File Reference
CCTWaterSurface.c File Reference
Data Structures
class CCTWaterSurface
Functions
void CCTWaterSurfaceEx (float maximal_target_distance, int allowedLiquidSource)
override bool Can (PlayerBase player, ActionTarget target)
bool CheckLiquidSource (vector hitPos, string surfaceName, int liquidType, int allowedWaterSourceMask)
int GetSurfaceLiquidType (ActionTarget target)
override bool CanContinue (PlayerBase player, ActionTarget target)
int GetLiquidType ()
Variables
CCTWaterSurface m_MaximalActionDistanceSq
protected int m_AllowedLiquidSource
protected int m_LiquidType = LIQUID_NONE
Function Documentation
Can()
override bool Can (PlayerBase player, ActionTarget target)
References CheckLiquidSource(), vector::DistanceSq(), GetSurfaceLiquidType(), m_AllowedLiquidSource, and m_MaximalActionDistanceSq.
CanContinue()
override bool CanContinue (PlayerBase player, ActionTarget target)
CCTWaterSurfaceEx()
void CCTWaterSurfaceEx (float maximal_target_distance, int allowedLiquidSource)
References m_AllowedLiquidSource, and m_MaximalActionDistanceSq.
Referenced by ActionFillBottleBase::ActionCondition(), ActionFillBottleBaseCB::CreateActionComponent(), CreateConditionComponents(), ActionFillBottleBase::CreateConditionComponents(), ActionFishingNew::CreateConditionComponents(), ActionInteractLoopBase::CreateConditionComponents(), and OnFinishProgressServer().
CheckLiquidSource()
bool CheckLiquidSource (vector hitPos, string surfaceName, int liquidType, int allowedWaterSourceMask)
Only return true if surface name is empty and
References g_Game, LIQUID_SALTWATER, and vector::Zero.
Referenced by Can().
GetLiquidType()
int GetLiquidType ()
References m_LiquidType.
Referenced by InventoryItem::GetItemOverheatThreshold(), InventoryItem::GetTemperatureFreezeThreshold(), InventoryItem::GetTemperatureThawThreshold(), InventoryItem::IsLiquidPresent(), InventoryItem::OnAction(), Barrel_ColorBase::OnFreezeStateChangeServer(), OnFreezeStateChangeServer(), InventoryItem::OnQuantityChanged(), and InventoryItem::WriteVarsToCTX().
GetSurfaceLiquidType()
int GetSurfaceLiquidType (ActionTarget target)
Check target surface liquid source first
Check target object for liquid source next
References LIQUID_NONE, and m_LiquidType.
Variable Documentation
m_AllowedLiquidSource
protected int m_AllowedLiquidSource
Referenced by Can(), and CCTWaterSurfaceEx().
m_LiquidType
protected int m_LiquidType = LIQUID_NONE
m_MaximalActionDistanceSq
CCTWaterSurface m_MaximalActionDistanceSq
Referenced by Can(), and CCTWaterSurfaceEx().