DayZ Scripts: ActionPushCarCB Class Reference
ActionPushCarCB Class Reference
Private Member Functions
override void CreateActionComponent ()
override protected void ApplyForce (ActionPushObjectData actionData)
Private Attributes
protected float PUSH_FORCE_IMPULSE_INCREMENT = 200.0
private ActionPushCarData m_ActionDataPushCar
Member Function Documentation
ApplyForce()
override protected void ApplyForce (ActionPushObjectData actionData) inline private
References dBodyApplyImpulseAt(), dBodyGetMass(), Easing::EaseInOutSine(), CarScript::GetPushForceCoefficientMultiplier(), m_ActionDataPushCar, ActionPushCarData::m_HorizontalDirectionRandom, ActionPushCarData::m_PushDirection, ActionPushCarData::m_VerticalDirectionRandom, PUSH_FORCE_IMPULSE_INCREMENT, and Math::RandomFloat().
CreateActionComponent()
override void CreateActionComponent () inline private
References UATimeSpent::PUSH_CAR.
Field Documentation
m_ActionDataPushCar
private ActionPushCarData m_ActionDataPushCar private
Referenced by ApplyForce().
PUSH_FORCE_IMPULSE_INCREMENT
protected float PUSH_FORCE_IMPULSE_INCREMENT = 200.0 private
Referenced by ApplyForce().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionPushCar.c