DayZ Scripts: ScriptConsoleSelector Class Reference
ScriptConsoleSelector Class Reference
Private Member Functions
void ScriptConsoleSelector (Widget parent, float value, ScriptConsoleTabBase parent_tab, bool disabled, float min, float max)
string GetLayoutFile ()
void SetColor (int color)
Widget GetLayoutRoot ()
ScriptConsoleTabBase GetTab ()
Private Attributes
protected ScriptConsoleTabBase m_ParentTab
Constructor & Destructor Documentation
ScriptConsoleSelector()
void ScriptConsoleSelector (Widget parent, float value, ScriptConsoleTabBase parent_tab, bool disabled, float min, float max) inline private
References WorkspaceWidget::CreateWidgets(), OptionSelectorSliderSetup::Enable(), GetGame(), GetLayoutFile(), CGame::GetWorkspace(), m_MaxValue, m_MinValue, m_Parent, m_ParentTab, m_Root, and SetValue().
Member Function Documentation
GetLayoutFile()
string GetLayoutFile () inline private
Referenced by ScriptConsoleSelector().
GetLayoutRoot()
Widget GetLayoutRoot () inline private
References m_Root.
Referenced by ScriptConsoleCameraTab::ToggleValueEditMode().
GetTab()
ScriptConsoleTabBase GetTab () inline private
References m_ParentTab.
SetColor()
void SetColor (int color) inline private
Field Documentation
m_ParentTab
protected ScriptConsoleTabBase m_ParentTab private
Referenced by GetTab(), and ScriptConsoleSelector().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptConsoleSelector.c