DayZ Scripts: CatchingContextFishingRodAction Class Reference
CatchingContextFishingRodAction Class Reference
Private Member Functions
override protected void Init (Param par)
override protected void InitCatchMethodMask ()
override protected void InitCatchEnviroMask ()
override protected void CreateResultDataStructure ()
override protected void ClearCatchingItemData ()
only clear stuff you need to update
override void InitCatchingItemData ()
override protected void InitItemValues (EntityAI item)
override bool ModifySignalProbability (inout float probability)
float GetChanceCoef ()
override bool RollCatch ()
protected void ResetSignalCounter ()
override void GenerateResult ()
done locally on both sides, needs a synced random
int GetResultParticleId ()
override protected void RecalculateProcessingData ()
float GetHookLossChanceModifierClamped ()
float GetBaitLossChanceModifierClamped ()
float GetActionCycleTime ()
float RandomizeSignalDuration ()
float RandomizeSignalStartTime ()
protected void TryHookLoss ()
protected void RemoveItemSafe (EntityAI item)
protected void TryBaitLoss ()
protected void TryDamageItems ()
override EntityAI SpawnAndSetupCatch (out int yItemIdx, vector v=vector.Zero)
void OnBeforeSpawnSignalHit ()
void OnAfterSpawnSignalHit ()
void OnSignalMiss ()
release without signal
void OnSignalPass ()
float GetSignalPoissonMean ()
Deprecated, left here due to inheritance change.
int GetSignalMax ()
Deprecated, left here due to inheritance change.
Private Attributes
protected PlayerBase m_Player
protected float m_BaitLossChanceMod
protected float m_HookLossChanceMod
protected float m_SignalDurationMin
protected float m_SignalDurationMax
protected float m_SignalStartTimeMin
protected float m_SignalStartTimeMax
protected float m_SignalCycleTarget
protected float m_SignalCycleEndTarget
protected float m_SignalCycleTargetAdjustment
protected float m_SignalCycleTargetEndAdjustment
protected float m_SignalTargetProbability
protected float m_SignalTargetEndProbability
protected int m_SignalCurrent
protected EntityAI m_Hook
protected EntityAI m_Bait
protected EntityAI m_Rod
protected float m_SignalPoissonMean = AnimalCatchingConstants.POISSON_CYCLE_MEAN_DEFAULT
Member Function Documentation
ClearCatchingItemData()
override protected void ClearCatchingItemData () inline private
only clear stuff you need to update
References m_BaitLossChanceMod, m_HookLossChanceMod, m_SignalCycleEndTarget, m_SignalCycleTarget, m_SignalCycleTargetAdjustment, m_SignalCycleTargetEndAdjustment, m_SignalDurationMax, m_SignalDurationMin, m_SignalStartTimeMax, m_SignalStartTimeMin, m_SignalTargetEndProbability, m_SignalTargetProbability, ResetSignalCounter(), UAFishingConstants::SIGNAL_CYCLE_HARD_TARGET_DEFAULT, UAFishingConstants::SIGNAL_CYCLE_MEAN_DEFAULT, UAFishingConstants::SIGNAL_HARD_TARGET_CHANCE_DEFAULT, and UAFishingConstants::SIGNAL_MEAN_CHANCE_DEFAULT.
CreateResultDataStructure()
override protected void CreateResultDataStructure () inline private
References m_MainItem, and m_Result.
GenerateResult()
override void GenerateResult () inline private
done locally on both sides, needs a synced random
References Class::CastTo(), m_Player, m_ProbabilityArray, m_Result, m_YieldsMapAll, and CatchingResultBasic::SetYieldItem().
GetActionCycleTime()
float GetActionCycleTime () inline private
References CarchingResultFishingAction::GetCurrentCycleTime(), and m_Result.
GetBaitLossChanceModifierClamped()
float GetBaitLossChanceModifierClamped () inline private
References Math::Clamp(), and m_BaitLossChanceMod.
Referenced by TryBaitLoss().
GetChanceCoef()
float GetChanceCoef () inline private
References UAFishingConstants::SIGNAL_FISHING_CHANCE_COEF.
Referenced by ModifySignalProbability().
GetHookLossChanceModifierClamped()
float GetHookLossChanceModifierClamped () inline private
References Math::Clamp(), and m_HookLossChanceMod.
Referenced by TryHookLoss().
GetResultParticleId()
int GetResultParticleId () inline private
References CatchingResultBasic::GetYieldItemParticleId(), ParticleList::INVALID, and m_Result.
GetSignalMax()
int GetSignalMax () inline private
Deprecated, left here due to inheritance change.
References Math::Ceil(), and m_SignalPoissonMean.
GetSignalPoissonMean()
float GetSignalPoissonMean () inline private
Deprecated, left here due to inheritance change.
References m_SignalPoissonMean.
Init()
override protected void Init (Param par) inline private
References m_MainItem, m_Player, and m_Rod.
InitCatchEnviroMask()
override protected void InitCatchEnviroMask () inline private
References m_EnviroMask, CatchingContextFishingBase::m_IsSea, AnimalCatchingConstants::MASK_ENVIRO_POND, and AnimalCatchingConstants::MASK_ENVIRO_SEA.
InitCatchingItemData()
override void InitCatchingItemData () inline private
References Math::Clamp(), IsCLIParam(), Debug::Log(), m_SignalCycleEndTarget, m_SignalCycleTarget, m_SignalCycleTargetAdjustment, m_SignalCycleTargetEndAdjustment, m_SignalDurationMax, m_SignalDurationMin, m_SignalStartTimeMax, m_SignalStartTimeMin, m_SignalTargetEndProbability, m_SignalTargetProbability, MAX, UAFishingConstants::SIGNAL_DURATION_MAX_BASE, UAFishingConstants::SIGNAL_DURATION_MIN_BASE, UAFishingConstants::SIGNAL_START_TIME_MAX_BASE, and UAFishingConstants::SIGNAL_START_TIME_MIN_BASE.
InitCatchMethodMask()
override protected void InitCatchMethodMask () inline private
References m_MethodMask, and AnimalCatchingConstants::MASK_METHOD_ROD.
InitItemValues()
override protected void InitItemValues (EntityAI item) inline private
References CFG_VEHICLESPATH, CGame::ConfigGetFloat(), GetGame(), m_Bait, m_BaitLossChanceMod, m_Hook, m_HookLossChanceMod, m_QualityBaseMod, m_QualityDispersionMaxMod, m_QualityDispersionMinMod, m_SignalCycleTargetAdjustment, m_SignalCycleTargetEndAdjustment, m_SignalDurationMax, m_SignalDurationMin, path, and slotName.
ModifySignalProbability()
override bool ModifySignalProbability (inout float probability) inline private
References Easing::EaseInExpo(), GetChanceCoef(), Math::InverseLerp(), IsCLIParam(), Debug::Log(), m_SignalCurrent, m_SignalCycleEndTarget, m_SignalCycleTarget, m_SignalTargetEndProbability, and m_SignalTargetProbability.
OnAfterSpawnSignalHit()
void OnAfterSpawnSignalHit () inline private
References m_Bait, RemoveItemSafe(), and TryDamageItems().
OnBeforeSpawnSignalHit()
void OnBeforeSpawnSignalHit () inline private
References TryHookLoss().
OnSignalMiss()
void OnSignalMiss () inline private
release without signal
References TryBaitLoss(), and TryHookLoss().
OnSignalPass()
void OnSignalPass () inline private
References m_Bait, RemoveItemSafe(), TryDamageItems(), and UpdateCatchingItemData().
RandomizeSignalDuration()
float RandomizeSignalDuration () inline private
References IsCLIParam(), Debug::Log(), m_Player, m_SignalDurationMax, and m_SignalDurationMin.
Referenced by RandomizeSignalValues().
RandomizeSignalStartTime()
float RandomizeSignalStartTime () inline private
References IsCLIParam(), Debug::Log(), m_Player, m_SignalStartTimeMax, and m_SignalStartTimeMin.
Referenced by RandomizeSignalValues().
RecalculateProcessingData()
override protected void RecalculateProcessingData () inline private
References m_Result, and CatchingResultBasic::UpdateCatchChance().
RemoveItemSafe()
protected void RemoveItemSafe (EntityAI item) inline private
References m_Player.
Referenced by OnAfterSpawnSignalHit(), OnSignalPass(), TryBaitLoss(), and TryHookLoss().
ResetSignalCounter()
protected void ResetSignalCounter () inline private
References m_SignalCurrent.
Referenced by ClearCatchingItemData().
RollCatch()
override bool RollCatch () inline private
References m_SignalCurrent.
Referenced by RollNextResultChance().
SpawnAndSetupCatch()
override EntityAI SpawnAndSetupCatch (out int yItemIdx, vector v = vector.Zero) inline private
References m_Hook.
TryBaitLoss()
protected void TryBaitLoss () inline private
References GetBaitLossChanceModifierClamped(), m_Bait, m_Player, and RemoveItemSafe().
Referenced by OnSignalMiss().
TryDamageItems()
protected void TryDamageItems () inline private
References UAFishingConstants::DAMAGE_HOOK, GetGame(), and m_Hook.
Referenced by OnAfterSpawnSignalHit(), and OnSignalPass().
TryHookLoss()
protected void TryHookLoss () inline private
References GetHookLossChanceModifierClamped(), m_Hook, m_Player, and RemoveItemSafe().
Referenced by OnBeforeSpawnSignalHit(), and OnSignalMiss().
Field Documentation
m_Bait
protected EntityAI m_Bait private
Referenced by InitItemValues(), OnAfterSpawnSignalHit(), OnSignalPass(), and TryBaitLoss().
m_BaitLossChanceMod
protected float m_BaitLossChanceMod private
Referenced by ClearCatchingItemData(), GetBaitLossChanceModifierClamped(), and InitItemValues().
m_Hook
protected EntityAI m_Hook private
Referenced by InitItemValues(), SpawnAndSetupCatch(), TryDamageItems(), and TryHookLoss().
m_HookLossChanceMod
protected float m_HookLossChanceMod private
Referenced by ClearCatchingItemData(), GetHookLossChanceModifierClamped(), and InitItemValues().
m_Player
protected PlayerBase m_Player private
Referenced by GenerateResult(), Init(), RandomizeSignalDuration(), RandomizeSignalStartTime(), RemoveItemSafe(), TryBaitLoss(), and TryHookLoss().
m_Rod
protected EntityAI m_Rod private
Referenced by Init().
m_SignalCurrent
protected int m_SignalCurrent private
Referenced by ModifySignalProbability(), ResetSignalCounter(), and RollCatch().
m_SignalCycleEndTarget
protected float m_SignalCycleEndTarget private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), and ModifySignalProbability().
m_SignalCycleTarget
protected float m_SignalCycleTarget private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), and ModifySignalProbability().
m_SignalCycleTargetAdjustment
protected float m_SignalCycleTargetAdjustment private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), and InitItemValues().
m_SignalCycleTargetEndAdjustment
protected float m_SignalCycleTargetEndAdjustment private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), and InitItemValues().
m_SignalDurationMax
protected float m_SignalDurationMax private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), InitItemValues(), and RandomizeSignalDuration().
m_SignalDurationMin
protected float m_SignalDurationMin private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), InitItemValues(), and RandomizeSignalDuration().
m_SignalPoissonMean
protected float m_SignalPoissonMean = AnimalCatchingConstants.POISSON_CYCLE_MEAN_DEFAULT private
Referenced by GetSignalMax(), and GetSignalPoissonMean().
m_SignalStartTimeMax
protected float m_SignalStartTimeMax private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), and RandomizeSignalStartTime().
m_SignalStartTimeMin
protected float m_SignalStartTimeMin private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), and RandomizeSignalStartTime().
m_SignalTargetEndProbability
protected float m_SignalTargetEndProbability private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), and ModifySignalProbability().
m_SignalTargetProbability
protected float m_SignalTargetProbability private
Referenced by ClearCatchingItemData(), InitCatchingItemData(), and ModifySignalProbability().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/AnimalCatchingSystem/CatchingContexts/CatchingContextFishingRodAction.c