DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionSawPlanks.c File Reference
ActionSawPlanks.c File Reference
Data Structures
class SawPlanksActionData
class ActionSawPlanks
Functions
override void CreateActionComponent ()
float GetDefaultTime ()
Variables
SawPlanksActionData TIME_SAW_HANDSAW = 1.5
static const float TIME_SAW_HACKSAW = 3.0
static const float TIME_AXES = 1.2
Function Documentation
CreateActionComponent()
override void CreateActionComponent ()
References GetDefaultTime().
GetDefaultTime()
float GetDefaultTime ()
References Debug::Log(), TIME_AXES, TIME_SAW_HACKSAW, and TIME_SAW_HANDSAW.
Referenced by CreateActionComponent().
Variable Documentation
TIME_AXES
const float TIME_AXES = 1.2 static
Referenced by GetDefaultTime().
TIME_SAW_HACKSAW
const float TIME_SAW_HACKSAW = 3.0 static
Referenced by GetDefaultTime().
TIME_SAW_HANDSAW
SawPlanksActionData TIME_SAW_HANDSAW = 1.5
Referenced by GetDefaultTime().