DayZ Scripts: API
API
Data Structures
class AbstractSoundScene
class SoundObject
class AbstractWaveEvents
Functions
SetSoundControllerOverride (string controllerName, float value, SoundControllerAction action)
proto native void MuteAllSoundControllers ()
proto native void ResetAllSoundControllers ()
private void AbstractSoundScene ()
private void ~AbstractSoundScene ()
proto native AbstractWave Play2D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
proto native AbstractWave Play3D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
proto native SoundObject BuildSoundObject (SoundObjectBuilder soundObjectbuilder)
proto native float GetRadioVolume ()
proto native void SetRadioVolume (float vol, float time)
proto native float GetSpeechExVolume ()
proto native void SetSpeechExVolume (float vol, float time)
proto native float GetMusicVolume ()
proto native void SetMusicVolume (float vol, float time)
proto native float GetSoundVolume ()
proto native void SetSoundVolume (float vol, float time)
proto native float GetVOIPVolume ()
proto native void SetVOIPVolume (float vol, float time)
proto native float GetSilenceThreshold ()
proto native float GetAudioLevel ()
class AbstractSoundScene SoundObjectBuilder (SoundParams soundParams)
private void AbstractSoundScene ()
private void ~AbstractSoundScene ()
proto native AbstractWave Play2D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
proto native AbstractWave Play3D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
proto native SoundObject BuildSoundObject (SoundObjectBuilder soundObjectbuilder)
proto native float GetRadioVolume ()
proto native void SetRadioVolume (float vol, float time)
proto native float GetSpeechExVolume ()
proto native void SetSpeechExVolume (float vol, float time)
proto native float GetMusicVolume ()
proto native void SetMusicVolume (float vol, float time)
proto native float GetSoundVolume ()
proto native void SetSoundVolume (float vol, float time)
proto native float GetVOIPVolume ()
proto native void SetVOIPVolume (float vol, float time)
proto native float GetSilenceThreshold ()
proto native float GetAudioLevel ()
SoundObject BuildSoundObject ()
proto native void Initialize (SoundParams soundParams)
proto native void AddEnvSoundVariables (vector position)
proto native void AddVariable (string name, float value)
proto void AddVariables (notnull array< string > names, array< float > values=null)
void UpdateEnvSoundControllers (vector position)
Deprecated - same functionality, just poor naming.
void SetVariable (string name, float value)
Deprecated - same functionality, just poor naming.
void SoundObject (SoundParams soundParams)
proto void UpdateVariables (notnull array< float > values)
proto native void SetParent (IEntity parent, int pivot=-1)
proto native IEntity GetParent ()
proto native int GetHierarchyPivot ()
proto native void SetPosition (vector position)
Note: Sets the position locally if parented, retrieves globally with the sound offset.
proto native vector GetPosition ()
proto native void SetSpeed (vector speed)
Note: Sets the speed locally if parented, retrieves globally with the parent speed.
proto native vector GetSpeed ()
proto native void SetOcclusionObstruction (float occlusion, float obstruction)
proto native void SetKind (WaveKind kind)
proto native void Initialize (SoundParams soundParams)
class SoundObject SoundParams (string name)
void SoundObject (SoundParams soundParams)
proto void UpdateVariables (notnull array< float > values)
proto native void SetParent (IEntity parent, int pivot=-1)
proto native IEntity GetParent ()
Get parent of the Effect.
proto native int GetHierarchyPivot ()
proto native void SetPosition (vector position)
Note: Sets the position locally if parented, retrieves globally with the sound offset.
proto native vector GetPosition ()
Get the world position of the Effect.
proto native void SetSpeed (vector speed)
Note: Sets the speed locally if parented, retrieves globally with the parent speed.
proto native vector GetSpeed ()
proto native void SetOcclusionObstruction (float occlusion, float obstruction)
proto native void SetKind (WaveKind kind)
proto native bool Load (string name)
proto native bool IsValid ()
Checks if the ScriptCaller is valid.
proto string GetName ()
Test name getter. Strictly for UI porposes!
class AbstractWaveEvents InitEvents ()
void AbstractWave ()
proto void SetUserData (Managed inst)
proto Managed GetUserData ()
proto void Play ()
void PlayWithOffset (float offset)
proto void Stop ()
Stops all elements this effect consists of.
proto void Restart ()
proto void SetStartOffset (float offset)
proto float GetLength ()
WARNING: Blocking! Waits for header to load.
proto float GetCurrPosition ()
Current position in percentage of total length.
proto void Loop (bool setLoop)
proto float GetVolume ()
proto void SetVolume (float value)
proto void SetVolumeRelative (float value)
proto void SetFrequency (float value)
proto float GetFrequency ()
proto void SetPosition (vector position, vector velocity="0 0 0")
proto void SetFadeInFactor (float volume)
proto void SetFadeOutFactor (float volume)
proto void SetDoppler (bool setDoppler)
proto void Skip (float timeSec)
proto bool IsHeaderLoaded ()
AbstractWaveEvents GetEvents ()
void OnPlay ()
void OnStop ()
void OnLoad ()
void OnHeaderLoad ()
void OnEnd ()
Variables
WAVEEFFECT
WAVEEFFECTEX
WAVESPEECH
WAVEMUSIC
WAVESPEECHEX
WAVEENVIRONMENT
WAVEENVIRONMENTEX
WAVEWEAPONS
WAVEWEAPONSEX
WAVEATTALWAYS
WAVEUI
None
Limit
ref ScriptInvoker Event_OnSoundWaveStarted = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveStopped = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveLoaded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveHeaderLoaded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveEnded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveStarted = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveStopped = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveLoaded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveHeaderLoaded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveEnded = new ScriptInvoker()
Detailed Description
Function Documentation
AbstractSoundScene() [1/2]
private void AbstractSoundScene ()
AbstractSoundScene() [2/2]
private void AbstractSoundScene () inline private
AbstractWave()
void AbstractWave ()
References InitEvents().
Referenced by ManBase::CheckSoundEvent(), DayZPlayer::HandleView(), DayZCreature::PlaySound(), EntityAI::PlaySound(), DayZPlayer::PlaySound(), DayZPlayer::ProcessSoundEvent(), DayZPlayer::ProcessVoiceEvent(), and DayZPlayer::ProcessWeaponEvent().
AddEnvSoundVariables()
proto native void AddEnvSoundVariables (vector position)
Referenced by UpdateEnvSoundControllers().
AddVariable()
proto native void AddVariable (string name, float value)
Referenced by SetVariable().
AddVariables()
proto void AddVariables (notnull array< string > names, array< float > values = null)
BuildSoundObject() [1/3]
SoundObject BuildSoundObject ()
References AbstractSoundScene::BuildSoundObject(), GetGame(), and CGame::GetSoundScene().
BuildSoundObject() [2/3]
proto native SoundObject BuildSoundObject (SoundObjectBuilder soundObjectbuilder)
BuildSoundObject() [3/3]
proto native SoundObject BuildSoundObject (SoundObjectBuilder soundObjectbuilder) private
Referenced by BuildSoundObject().
GetAudioLevel() [1/2]
proto native float GetAudioLevel ()
Referenced by ScriptedWidgetEventHandler::UpdateAudioLevel().
GetAudioLevel() [2/2]
proto native float GetAudioLevel () private
GetCurrPosition()
proto float GetCurrPosition ()
Current position in percentage of total length.
GetEvents()
AbstractWaveEvents GetEvents ()
References GetUserData().
GetFrequency()
proto float GetFrequency ()
GetHierarchyPivot() [1/2]
proto native int GetHierarchyPivot ()
GetHierarchyPivot() [2/2]
proto native int GetHierarchyPivot () private
GetLength()
proto float GetLength ()
WARNING: Blocking! Waits for header to load.
GetMusicVolume() [1/2]
proto native float GetMusicVolume ()
GetMusicVolume() [2/2]
proto native float GetMusicVolume () private
Referenced by CGame::DeferredInit().
GetName()
proto string GetName ()
Test name getter. Strictly for UI porposes!
Gets the name which is set for the ParticleManager, default is "ParticleSourceManager".
Suite class name getter. Strictly for UI porposes!
References m_Name, and name.
GetParent() [1/2]
proto native IEntity GetParent ()
Get parent of the Effect.
Note
Same as GetAttachmentParent, but more generic name
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
Object The parent of the Effect
References m_Parent.
GetParent() [2/2]
proto native IEntity GetParent () private
Referenced by EffectSound::GetCurrentParent(), and EffectSound::GetParent().
GetPosition() [1/2]
proto native vector GetPosition ()
Get the world position of the Effect.
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
vector The world position of the Effect
References m_AreaPosition, and m_Position.
Referenced by FireplaceBase::AfterStoreLoad(), ManBase::AfterStoreLoad(), UIScriptedMenu::CameraToolsMenu(), DayZInfected::ChaseAttackLogic(), CheckAllowUpdate(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), CreateLight(), Grenade_Base::CreateLight(), ItemBase::CreateRope(), CreateTrigger(), Entity::DeathUpdate(), DayZAnimal::DeathUpdate(), BoatScript::DecayHealthTick(), KitBase::DisassembleKit(), ItemBase::DoMeasurement(), ScriptConsoleItemsTab::DrawItems(), ManBase::DropItem(), ContaminatedArea_Dynamic::EEInit(), House::EEInit(), GeyserTrigger::EEInit(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), FlammableBase::EEItemDetached(), Ammo_40mm_Explosive::EEKilled(), ContaminatedArea_Dynamic::EEOnCECreate(), Inventory_Base::EmptySeedPack(), InventoryItem::EOnContact(), DynamicArea_Flare::EOnFrame(), DayZSpectator::EOnFrame(), FireplaceBase::EOnTouch(), EOnTouch(), DayZInfected::EvaluateCrawlTransitionAnimation(), DayZPlayer::EvaluateDamageHitAnimation(), DayZPlayer::EvaluateDeathAnimation(), Hit_MeatBones::Event_OnStarted(), IEntity::Explode(), Explode(), CGame::ExplosionEffects(), ExplosivesBase(), DayZInfected::FightAttackLogic(), DayZInfected::FightLogic(), BoatScript::FlipVehicle(), GenerateCarHornAINoise(), DayZInfected::GetAttackPitch(), WorldData::GetBaseEnvTemperatureAtObject(), GetCeilingHeight(), IEntity::GetCenter(), Land_WarheadStorage_PowerStation::GetClosestBunker(), GetClosestCarWheel(), GetClosestDoor(), EffectSound::GetCurrentLocalPosition(), EffectSound::GetCurrentPosition(), GetEmptyingEndSoundset(), GetEmptyingLoopSoundset(), ItemBase::GetKitSpawnPosition(), BaseBuildingBase::GetKitSpawnPosition(), IEntity::GetSurfaceNoise(), Entity::GetUniversalTemperatureSourcePosition(), BoatScript::HandleBoatSplashSound(), EntityLightSource::HandleDancingShadows(), HandleDoorsSound(), BaseBuildingBase::HandleRefreshers(), HandleSeatAdjustmentSound(), DayZPlayer::HandleView(), Heating(), BaseBuildingBase::InsertRefresherPosition(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), ManBase::IsFacingTarget(), BaseBuildingBase::IsPlayerInside(), TentBase::IsPlayerInside(), ItemBase::IsPlayerInVicinity(), RemoteDetonatorTrigger::OnActivatedByItem(), CarScript::OnAnimationPhaseStarted(), OnCEUpdate(), RemoteDetonatorTrigger::OnCEUpdate(), BaseBuildingBase::OnCEUpdate(), ManBase::OnConnect(), Grenade_ChemGas::OnDamageDestroyed(), ClaymoreMine::OnDebugSpawn(), RifleSingleShot_Base::OnDebugSpawn(), KitBase::OnDebugSpawn(), OnDebugSpawn(), FishingRod_Base_New::OnDebugSpawn(), Crossbow_Base::OnDebugSpawnEx(), FireworksLauncher::OnEventServer(), Anniversary_FireworksLauncher::OnEventServer(), Grenade_ChemGas::OnExplode(), IEntity::OnExplodeClient(), Weapon::OnFireModeChange(), FireworksLauncher::OnFuseIgnitedClient(), PluginBase::OnGUITimer(), FireplaceBase::OnIgnitedThis(), GardenBase::OnPlacementComplete(), KitBase::OnPlacementComplete(), InventoryItem::OnRPC(), CGame::OnRPC(), DayZPlayer::OnStepEvent(), OnSteppedOn(), GardenBase::OnStoreLoad(), ItemBase::OnStoreLoad(), AlarmClock_ColorBase::OnUpdate(), KitchenTimer::OnUpdate(), BotStateBase::OnUpdate(), AnniversarySpotLight::OnVariablesSynchronized(), BoatScript::OnVariablesSynchronized(), InventoryItemSuper::OnWasAttached(), InventoryItemSuper::OnWasDetached(), OnWork(), OnWorkStart(), ItemBase::ParticleTest(), BaseBuildingBase::PerformRoofCheckForBase(), ItemBase::PlaceOnGround(), InventoryItem::PlayAttachSound(), PlayDisarmingLoopSound(), EntityAI::PlayImpactSound(), PlayRepackingLoopSound(), Backpack_Base::PlayRepackingLoopSound(), DayZCreature::PlaySound(), EntityAI::PlaySound(), DayZPlayer::PlaySound(), BoatScript::PlaySound(), PlaySoundActivate(), TrapBase::PlaySoundBiteEmpty(), TrapBase::PlaySoundBiteLeg(), PlaySoundEx(), TrapBase::PlaySoundOpen(), PlayVFX(), Environment::ProcessItemsDryness(), DayZCreature::ProcessSoundEvent(), DayZPlayer::ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), RefreshFireplaceVisuals(), BaseBuildingBase::RemoveRefresherPosition(), House::RequestSoundEvent(), ManBase::SaySoundSet(), ManBase::SetContaminatedEffectEx(), SetParticlePosition(), BaseBuildingBase::SetRefresherActive(), Edible_Base::SoundCookingStart(), Entity::SoundHardBushFallingPlay(), Entity::SoundHardTreeFallingPlay(), EffectSound::SoundLoadEx(), EffectSound::SoundPlayEx(), Entity::SoundSoftBushFallingPlay(), Entity::SoundSoftTreeFallingPlay(), ManBase::SpawnEntityOnGroundOnCursorDir(), TentBase::SpawnKit(), PluginBase::SpawnNewInfectedEntity(), CrashBase::SpawnRandomDeers(), UndergroundTriggerCarrierBase::SpawnTrigger(), HotSpringTrigger::SpawnVaporEffect(), VolcanicTrigger::SpawnVaporEffect(), FlammableBase::StandUp(), EffectParticle::Start(), StartActivate(), Particle::StopParticle(), TestOwnership(), EntityLightSource::TryShadowOptimization(), FlammableBase::TryTransformIntoStick(), AreaDamageTriggerBase::UpdateInsiders(), UpdateMusic(), ManBase::UpdatePlayerMeasures(), ScriptedWidgetEventHandler::UpdatePos(), and ItemBase::UpdatePreyPos().
GetPosition() [2/2]
proto native vector GetPosition () private
Referenced by EffectSound::GetCurrentLocalPosition(), and EffectSound::GetCurrentPosition().
GetRadioVolume() [1/2]
proto native float GetRadioVolume ()
GetRadioVolume() [2/2]
proto native float GetRadioVolume () private
Referenced by CGame::DeferredInit().
GetSilenceThreshold() [1/2]
proto native float GetSilenceThreshold ()
GetSilenceThreshold() [2/2]
proto native float GetSilenceThreshold () private
Referenced by VONManager::IsVoiceThresholdMinimum().
GetSoundVolume() [1/2]
proto native float GetSoundVolume ()
GetSoundVolume() [2/2]
proto native float GetSoundVolume () private
Referenced by CGame::DeferredInit().
GetSpeechExVolume() [1/2]
proto native float GetSpeechExVolume ()
GetSpeechExVolume() [2/2]
proto native float GetSpeechExVolume () private
Referenced by CGame::DeferredInit().
GetSpeed() [1/2]
proto native vector GetSpeed ()
GetSpeed() [2/2]
proto native vector GetSpeed () private
GetUserData()
proto Managed GetUserData ()
Referenced by GetEvents().
GetVOIPVolume() [1/2]
proto native float GetVOIPVolume ()
GetVOIPVolume() [2/2]
proto native float GetVOIPVolume () private
Referenced by CGame::DeferredInit().
GetVolume()
proto float GetVolume ()
InitEvents()
class AbstractWaveEvents InitEvents ()
Referenced by AbstractWave().
Initialize() [1/2]
proto native void Initialize (SoundParams soundParams)
Initialize() [2/2]
proto native void Initialize (SoundParams soundParams) private
IsHeaderLoaded()
proto bool IsHeaderLoaded ()
IsValid()
proto native bool IsValid ()
Checks if the ScriptCaller is valid.
Checks if the ScriptCaller is valid.
References discreteItemSets, Debug::Log(), m_IsValid, and slotName.
Load()
proto native bool Load (string name)
Loop()
proto void Loop (bool setLoop)
MuteAllSoundControllers()
proto native void MuteAllSoundControllers ()
Overrides all the environment controllers to be muted
OnEnd()
void OnEnd ()
References GetEvents().
Referenced by ActionBase::End(), and AnimatedActionBase::End().
OnHeaderLoad()
void OnHeaderLoad ()
References GetEvents().
OnLoad()
void OnLoad ()
References GetEvents().
OnPlay()
void OnPlay ()
References GetEvents().
OnStop()
void OnStop ()
References GetEvents().
Referenced by PPERequesterBase::Stop().
Play()
override EAnimPlayState Play ()
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLaterByName(), Error(), AbstractWaveEvents::Event_OnSoundWaveEnded, AbstractWaveEvents::Event_OnSoundWaveStopped, string::Format(), CGame::GetCallQueue(), GetGame(), CGame::GetTime(), HumanCommandAdditives(), ScriptInvoker::Insert(), HumanCommandWeapons::IsActionFinished(), IsDummy(), m_AnimID, m_DummyStartTime, m_Infected, m_IsPlaying, m_Player, m_SoundSetCallback, m_SoundSetNameRoot, m_SoundVoiceAnimEventClassID, PlayerSoundEventBase::OnEnd(), OnInterupt(), PrintToRPT(), and DayZPlayer::ProcessVoiceEvent().
Referenced by UIScriptedMenu::OnClick(), UIScriptedMenu::OnKeyPress(), and PlayWithOffset().
Play2D() [1/2]
proto native AbstractWave Play2D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
Play2D() [2/2]
proto native AbstractWave Play2D (SoundObject soundObject, SoundObjectBuilder soundBuilder) private
Referenced by MissionBase::PlayMusic(), and DynamicMusicPlayer::PlayTrack().
Play3D() [1/2]
proto native AbstractWave Play3D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
Play3D() [2/2]
proto native AbstractWave Play3D (SoundObject soundObject, SoundObjectBuilder soundBuilder) private
Referenced by DayZPlayer::HandleView(), PluginBase::OnGUITimer(), DayZCreature::PlaySound(), EntityAI::PlaySound(), DayZPlayer::PlaySound(), ManBase::SaySoundSet(), and EffectSound::SoundPlayEx().
PlayWithOffset()
void PlayWithOffset (float offset)
References Play(), and SetStartOffset().
ResetAllSoundControllers()
proto native void ResetAllSoundControllers ()
Removes all the previously set overrides of sound controllers
Restart()
proto void Restart ()
SetDoppler()
proto void SetDoppler (bool setDoppler)
SetFadeInFactor()
proto void SetFadeInFactor (float volume)
SetFadeOutFactor()
proto void SetFadeOutFactor (float volume)
SetFrequency()
proto void SetFrequency (float value)
SetKind() [1/2]
proto native void SetKind (WaveKind kind)
SetKind() [2/2]
proto native void SetKind (WaveKind kind) private
Referenced by DayZCreature::AttenuateSoundIfNecessary(), DayZPlayer::AttenuateSoundIfNecessary(), EntityAI::PlayImpactSound(), MissionBase::PlayMusic(), DynamicMusicPlayer::PlayTrack(), EffectSound::SoundLoadEx(), and EffectSound::SoundPlayEx().
SetMusicVolume() [1/2]
proto native void SetMusicVolume (float vol, float time)
SetMusicVolume() [2/2]
proto native void SetMusicVolume (float vol, float time) private
Referenced by MissionBase::OnPlayerRespawned(), and DayZPlayer::SimulateDeath().
SetOcclusionObstruction() [1/2]
proto native void SetOcclusionObstruction (float occlusion, float obstruction)
SetOcclusionObstruction() [2/2]
proto native void SetOcclusionObstruction (float occlusion, float obstruction) private
SetParent() [1/2]
proto native void SetParent (IEntity parent, int pivot = -1)
Note: 'SoundObject' is not an Entity, and therefore can not be accessed by using 'IEntity.GetChildren', though internally 'SoundObject.SetParent' is similiar to 'IEntity.AddChild' by creating an 'EntityHierarchyComponent'
SetParent() [2/2]
proto native void SetParent (IEntity parent, int pivot = -1) private
Note: 'SoundObject' is not an Entity, and therefore can not be accessed by using 'IEntity.GetChildren', though internally 'SoundObject.SetParent' is similiar to 'IEntity.AddChild' by creating an 'EntityHierarchyComponent'
Referenced by EffectSound::SetParent(), EffectSound::SoundLoadEx(), and EffectSound::SoundPlayEx().
SetPosition() [1/3]
proto native void SetPosition (vector pos)
Note: Sets the position locally if parented, retrieves globally with the sound offset.
Note: Sets the position locally if parented, retrieves globally with the sound offset.
Warning
Only sets the cached variable, for immediate effect use SetCurrent variant
Parameters
pos vector The world position for the Effect
SetPosition() [2/3]
proto native void SetPosition (vector position) private
Note: Sets the position locally if parented, retrieves globally with the sound offset.
Referenced by DayZPlayer::HandleView(), DayZCreature::PlaySound(), EntityAI::PlaySound(), DayZPlayer::PlaySound(), EffectSound::SetCurrentLocalPosition(), and EffectSound::SetCurrentPosition().
SetPosition() [3/3]
proto void SetPosition (vector position, vector velocity = "0 0 0")
SetRadioVolume() [1/2]
proto native void SetRadioVolume (float vol, float time)
SetRadioVolume() [2/2]
proto native void SetRadioVolume (float vol, float time) private
Referenced by MissionBase::OnPlayerRespawned(), and DayZPlayer::SimulateDeath().
SetSoundControllerOverride()
SetSoundControllerOverride (string controllerName, float value, SoundControllerAction action)
Overrides or limits soundmap value for a sound cotroller
Parameters
controllerName the sound controller name. One of: rain,night,meadow,trees,hills,houses,windy,deadBody,sea,forest,altitudeGround,altitudeSea,altitudeSurface,daytime,shooting,coast,waterDepth,overcast,fog,snowfall,caveSmall,caveBig
action what action will be used on the normal landscape sound controller value
value the new value of sound controller
Referenced by PlayAmbientSound(), and StopAmbientSound().
SetSoundVolume() [1/2]
proto native void SetSoundVolume (float vol, float time)
SetSoundVolume() [2/2]
proto native void SetSoundVolume (float vol, float time) private
Referenced by UIScriptedMenu::OnHide(), MissionBase::OnPlayerRespawned(), UIScriptedMenu::OnShow(), ManBase::OnUnconsciousStart(), ManBase::OnUnconsciousStop(), and DayZPlayer::SimulateDeath().
SetSpeechExVolume() [1/2]
proto native void SetSpeechExVolume (float vol, float time)
SetSpeechExVolume() [2/2]
proto native void SetSpeechExVolume (float vol, float time) private
Referenced by MissionBase::OnPlayerRespawned(), and DayZPlayer::SimulateDeath().
SetSpeed() [1/2]
proto native void SetSpeed (vector speed)
Note: Sets the speed locally if parented, retrieves globally with the parent speed.
SetSpeed() [2/2]
proto native void SetSpeed (vector speed) private
Note: Sets the speed locally if parented, retrieves globally with the parent speed.
SetStartOffset()
proto void SetStartOffset (float offset)
Referenced by PlayWithOffset().
SetUserData()
proto void SetUserData (Managed inst)
SetVariable()
void SetVariable (string name, float value)
Deprecated - same functionality, just poor naming.
References AddVariable(), and name.
SetVOIPVolume() [1/2]
proto native void SetVOIPVolume (float vol, float time)
SetVOIPVolume() [2/2]
proto native void SetVOIPVolume (float vol, float time) private
Referenced by MissionBase::OnPlayerRespawned(), and DayZPlayer::SimulateDeath().
SetVolume()
proto void SetVolume (float value)
SetVolumeRelative()
proto void SetVolumeRelative (float value)
Skip()
proto void Skip (float timeSec)
SoundObject() [1/2]
void SoundObject (SoundParams soundParams)
SoundObject() [2/2]
void SoundObject (SoundParams soundParams) private
SoundObjectBuilder()
class AbstractSoundScene SoundObjectBuilder (SoundParams soundParams)
Referenced by DayZPlayerTypeVoiceSoundLookupTable::GetSoundBuilder(), DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder(), GetSoundBuilder(), DayZPlayer::HandleView(), SoundLookupTable::LoadTable(), LoadVegetationSounds(), PluginBase::OnGUITimer(), DayZPlayer::OnStepEvent(), EntityAI::PlayImpactSound(), MissionBase::PlayMusic(), EntityAI::PlaySoundByAnimEvent(), DynamicMusicPlayer::PlayTrack(), DayZPlayer::ProcessAttachmentEvent(), DayZCreature::ProcessSoundEvent(), DayZPlayer::ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), DayZPlayer::ProcessVoiceEvent(), DayZInfected::ProcessVoiceFX(), DayZPlayer::ProcessWeaponEvent(), ManBase::SaySoundSet(), and EffectSound::SoundLoadEx().
SoundParams()
class SoundObject SoundParams (string name)
Referenced by SEffectManager::GetCachedSoundParam(), DayZPlayer::HandleView(), LoadVegetationSounds(), PluginBase::OnGUITimer(), MissionBase::PlayMusic(), SEffectManager::PlaySoundCachedParams(), DynamicMusicPlayer::PlayTrack(), DayZInfected::ProcessVoiceFX(), ManBase::SaySoundSet(), EffectSound::SoundLoad(), EffectSound::SoundLoadEx(), and EffectSound::SoundPlay().
Stop()
proto void Stop ()
Stops all elements this effect consists of.
Note
Alternatively use SEffectManager.Stop(effect_id)
Stops all elements this effect consists of.
References CALL_CATEGORY_GAMEPLAY, Event_OnStopped, CGame::GetCallQueue(), GetGame(), ScriptInvoker::Invoke(), IsPlaying(), m_CommandSync, m_CurrentState, m_SoundSetCallback, m_time, Process(), ScriptCallQueue::RemoveByName(), and SetRunning().
Referenced by Destroy(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnKeyPress(), PPERequester_GameplayBase::OnUpdate(), UIScriptedMenu::Update(), UIScriptedMenu::~CameraToolsMenu(), and ~Effect().
UpdateEnvSoundControllers()
void UpdateEnvSoundControllers (vector position)
Deprecated - same functionality, just poor naming.
References AddEnvSoundVariables().
UpdateVariables() [1/2]
proto void UpdateVariables (notnull array< float > values)
UpdateVariables() [2/2]
proto void UpdateVariables (notnull array< float > values) private
~AbstractSoundScene() [1/2]
private void ~AbstractSoundScene ()
~AbstractSoundScene() [2/2]
private void ~AbstractSoundScene () inline private
Variable Documentation
Event_OnSoundWaveEnded [1/2]
ref ScriptInvoker Event_OnSoundWaveEnded = new ScriptInvoker() private
Referenced by Play(), and EffectSound::ValidateSoundWave().
Event_OnSoundWaveEnded [2/2]
ref ScriptInvoker Event_OnSoundWaveEnded = new ScriptInvoker()
Event_OnSoundWaveHeaderLoaded [1/2]
ref ScriptInvoker Event_OnSoundWaveHeaderLoaded = new ScriptInvoker() private
Event_OnSoundWaveHeaderLoaded [2/2]
ref ScriptInvoker Event_OnSoundWaveHeaderLoaded = new ScriptInvoker()
Event_OnSoundWaveLoaded [1/2]
ref ScriptInvoker Event_OnSoundWaveLoaded = new ScriptInvoker() private
Event_OnSoundWaveLoaded [2/2]
ref ScriptInvoker Event_OnSoundWaveLoaded = new ScriptInvoker()
Event_OnSoundWaveStarted [1/2]
ref ScriptInvoker Event_OnSoundWaveStarted = new ScriptInvoker() private
Referenced by EffectSound::ValidateSoundWave().
Event_OnSoundWaveStarted [2/2]
ref ScriptInvoker Event_OnSoundWaveStarted = new ScriptInvoker()
Event_OnSoundWaveStopped [1/2]
ref ScriptInvoker Event_OnSoundWaveStopped = new ScriptInvoker() private
Referenced by Play().
Event_OnSoundWaveStopped [2/2]
ref ScriptInvoker Event_OnSoundWaveStopped = new ScriptInvoker()
Limit
Limit
Referenced by UpdateLRAngle(), UpdateLRAngleLookAt(), UpdateLRAngleUnlocked(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
None
None
WAVEATTALWAYS
WAVEATTALWAYS
WAVEEFFECT
WAVEEFFECT
WAVEEFFECTEX
WAVEEFFECTEX
WAVEENVIRONMENT
WAVEENVIRONMENT
WAVEENVIRONMENTEX
WAVEENVIRONMENTEX
WAVEMUSIC
WAVEMUSIC
WAVESPEECH
WAVESPEECH
WAVESPEECHEX
WAVESPEECHEX
WAVEUI
WAVEUI
WAVEWEAPONS
WAVEWEAPONS
WAVEWEAPONSEX
WAVEWEAPONSEX