DayZ Scripts: P:/scripts/4_World/Entities/GardenBase/PlantBase.c File Reference
PlantBase.c File Reference
Enumerations
enum EPlantState {
PAUSED = 0 , GROWING , MATURE , SPOILED ,
DRY
}
Functions
void PlantBase ()
void ~PlantBase ()
void Init (GardenBase garden_base, float fertility, float harvesting_efficiency, float water)
void Tick ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
string GetCropsType ()
bool OnStoreLoadCustom (ParamsReadContext ctx, int version)
void OnStoreSaveCustom (ParamsWriteContext ctx)
void PrintValues ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanRemoveFromHands (EntityAI parent)
void ChangeInfestation (bool is_infested)
void UpdatePlant ()
void GrowthTimerTick ()
void SetSpoiled ()
void SetDry ()
void SprayPlant (float consumed_quantity)
void RemovePlantEx (vector pos)
void DestroyPlant ()
void Harvest (PlayerBase player)
void SetPlantState (int state)
EPlantState GetPlantState ()
int GetPlantStateIndex ()
float GetWater ()
float GetWaterMax ()
bool NeedsWater ()
float GetSprayQuantity ()
float GetSprayUsage ()
void RemoveSlot ()
void SetSlot (Slot slot)
Slot GetSlot ()
void SetGarden (GardenBase gardenBase)
GardenBase GetGarden ()
bool IsSprayable ()
bool IsHarvestable ()
bool HasCrops ()
override void SetActions ()
void DebugSetTimes (int maturity, int spoil, int spoilRemove, int dryDelete)
static void DebugSetGlobalTimes (int maturity, int spoil, int spoilRemove, int dryDelete)
static void DebugSetTickSpeedMultiplier (float multiplier)
void DeleteDryPlantTick ()
void SpoiledRemoveTimerTick ()
void InfestationTimerTick ()
void CheckWater ()
bool IsMature ()
bool IsSpoiled ()
bool IsDry ()
bool IsGrowing ()
bool NeedsSpraying ()
void RemovePlant ()
string StopInfestation (float consumed_quantity)
Variables
enum EPlantState m_SprayUsage
private float m_InfestationChance
private int m_GrowthStagesCount
private int m_CropsCount
private bool m_HasCrops
private string m_CropsType
private float m_PlantMaterialMultiplier
private int m_PlantStateIndex
private float m_CurrentPlantMaterialQuantity
protected EPlantState m_PlantState
private bool m_IsInfested
private float m_SprayQuantity
bool m_MarkForDeletion = false
int m_DeleteDryPlantTime
int m_SpoiledRemoveTime
int m_FullMaturityTime
int m_SpoilAfterFullMaturityTime
float m_StateChangeTime
protected ref Timer m_TimeTicker
protected float m_TimeTracker
private GardenBase m_GardenBase = NULL
private ref Slot m_Slot = NULL
private PluginHorticulture m_ModuleHorticulture
private const float SPOIL_AFTER_MATURITY_TIME = 14400.0
private const int TICK_FREQUENCY = 1
static int m_DebugFullMaturityTime
static int m_DebugSpoilTime
static int m_DebugSpoilRemoveTime
static int m_DebugDeleteDryTime
static float m_DebugTickSpeedMultiplier = 1
static const int STATE_DRY = 0
static const int STATE_GROWING = 1
static const int STATE_MATURE = 2
static const int STATE_SPOILED = 3
ref Timer m_SpoiledRemoveTimer
ref Timer m_DeleteDryPlantTimer
ref Timer m_SpoilAfterFullMaturityTimer
ref Timer m_GrowthTimer
ref Timer m_InfestationTimer
Enumeration Type Documentation
EPlantState
enum EPlantState
Enumerator
PAUSED
GROWING
MATURE
SPOILED
DRY
Function Documentation
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent)
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI parent)
CanRemoveFromHands()
override bool CanRemoveFromHands (EntityAI parent)
ChangeInfestation()
void ChangeInfestation (bool is_infested)
References GetType(), PlantMaterialHealth::m_HealthyMat, PlantMaterialHealth::m_HealthyTex, PlantMaterialHealth::m_InfestedMat, PlantMaterialHealth::m_InfestedTex, m_IsInfested, and m_ModuleHorticulture.
Referenced by GrowthTimerTick(), and SprayPlant().
CheckWater()
void CheckWater ()
DebugSetGlobalTimes()
static void DebugSetGlobalTimes (int maturity, int spoil, int spoilRemove, int dryDelete) static
References m_DebugDeleteDryTime, m_DebugFullMaturityTime, m_DebugSpoilRemoveTime, and m_DebugSpoilTime.
DebugSetTickSpeedMultiplier()
static void DebugSetTickSpeedMultiplier (float multiplier) static
References m_DebugTickSpeedMultiplier.
DebugSetTimes()
void DebugSetTimes (int maturity, int spoil, int spoilRemove, int dryDelete)
References m_DeleteDryPlantTime, m_FullMaturityTime, m_GrowthStagesCount, m_SpoilAfterFullMaturityTime, m_SpoiledRemoveTime, and m_StateChangeTime.
DeleteDryPlantTick()
void DeleteDryPlantTick ()
DestroyPlant()
void DestroyPlant ()
References GetGame(), RemoveSlot(), and UnlockFromParent().
Referenced by ~PlantBase().
GetCropsType()
string GetCropsType ()
References m_CropsType.
GetGarden()
GardenBase GetGarden ()
References m_GardenBase.
GetPlantState()
EPlantState GetPlantState ()
References m_PlantState.
GetPlantStateIndex()
int GetPlantStateIndex ()
References m_PlantStateIndex.
GetSlot()
Slot GetSlot ()
References m_Slot.
Referenced by GetWater(), GetWaterMax(), and OnStoreSave().
GetSprayQuantity()
float GetSprayQuantity ()
References m_SprayQuantity.
GetSprayUsage()
float GetSprayUsage ()
References m_SprayUsage.
GetWater()
float GetWater ()
References GetSlot().
GetWaterMax()
float GetWaterMax ()
References GetSlot().
GrowthTimerTick()
void GrowthTimerTick ()
References ChangeInfestation(), m_GrowthStagesCount, m_InfestationChance, m_IsInfested, m_PlantStateIndex, m_TimeTracker, Math::RandomFloat01(), SetDry(), SetPlantState(), and UpdatePlant().
Referenced by Init(), and Tick().
Harvest()
void Harvest (PlayerBase player)
References ECE_PLACE_ON_SURFACE, GetGame(), IsHarvestable(), m_CropsCount, m_CropsType, m_GardenBase, m_HasCrops, ItemBase::SetQuantity(), and UpdatePlant().
HasCrops()
bool HasCrops ()
References m_HasCrops.
Referenced by UpdatePlant().
InfestationTimerTick()
void InfestationTimerTick ()
Init()
void Init (GardenBase garden_base, float fertility, float harvesting_efficiency, float water)
References Math::Ceil(), WeatherPhenomenon::GetActual(), GetGame(), Weather::GetRain(), CGame::GetWeather(), GrowthTimerTick(), m_CropsCount, m_DebugDeleteDryTime, m_DebugFullMaturityTime, m_DebugSpoilRemoveTime, m_DebugSpoilTime, m_DeleteDryPlantTime, m_FullMaturityTime, m_GardenBase, m_GrowthStagesCount, m_PlantMaterialMultiplier, m_PlantState, m_SpoilAfterFullMaturityTime, m_SpoiledRemoveTime, m_StateChangeTime, NeedsWater(), Math::RandomInt(), SetPlantState(), and SPOIL_AFTER_MATURITY_TIME.
IsDry()
bool IsDry ()
IsGrowing()
bool IsGrowing ()
IsHarvestable()
bool IsHarvestable ()
References m_HasCrops, and m_PlantState.
Referenced by Harvest().
IsMature()
bool IsMature ()
IsSpoiled()
bool IsSpoiled ()
IsSprayable()
bool IsSprayable ()
References m_PlantState, m_SprayQuantity, and m_SprayUsage.
NeedsSpraying()
bool NeedsSpraying ()
NeedsWater()
bool NeedsWater ()
References m_PlantState, and m_Slot.
Referenced by Init().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
References OnStoreLoadCustom(), Serializer::Read(), and SetSlot().
OnStoreLoadCustom()
bool OnStoreLoadCustom (ParamsReadContext ctx, int version)
References ErrorEx, GetPosition, m_CropsCount, m_CropsType, m_CurrentPlantMaterialQuantity, m_DeleteDryPlantTime, m_FullMaturityTime, m_GrowthStagesCount, m_HasCrops, m_InfestationChance, m_IsInfested, m_PlantMaterialMultiplier, m_PlantState, m_PlantStateIndex, m_SpoilAfterFullMaturityTime, m_SpoiledRemoveTime, m_SprayQuantity, m_SprayUsage, m_StateChangeTime, m_TimeTracker, Serializer::Read(), and UpdatePlant().
Referenced by OnStoreLoad().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
References ErrorEx, GetGame(), GetPosition, GetSlot(), CGame::ObjectDelete(), OnStoreSaveCustom(), and Serializer::Write().
OnStoreSaveCustom()
void OnStoreSaveCustom (ParamsWriteContext ctx)
References m_CropsCount, m_CropsType, m_CurrentPlantMaterialQuantity, m_DeleteDryPlantTime, m_FullMaturityTime, m_GrowthStagesCount, m_HasCrops, m_InfestationChance, m_IsInfested, m_PlantMaterialMultiplier, m_PlantState, m_PlantStateIndex, m_SpoilAfterFullMaturityTime, m_SpoiledRemoveTime, m_SprayQuantity, m_SprayUsage, m_StateChangeTime, m_TimeTracker, and Serializer::Write().
Referenced by OnStoreSave().
PlantBase()
void PlantBase ()
References CALL_CATEGORY_SYSTEM, CGame::ConfigGetInt(), CGame::ConfigGetText(), GetGame(), GetPlugin(), GetType(), m_CropsCount, m_CropsType, m_CurrentPlantMaterialQuantity, m_DeleteDryPlantTime, m_GrowthStagesCount, m_HasCrops, m_InfestationChance, m_IsInfested, m_ModuleHorticulture, m_PlantStateIndex, m_SpoiledRemoveTime, m_SprayQuantity, m_SprayUsage, m_TimeTicker, Math::RandomInt(), SetTakeable(), and TICK_FREQUENCY.
Referenced by ActionDisinfectPlant::ActionCondition(), ActionWaterPlant::ActionCondition(), ActionHarvestCrops::ActionCondition(), ActionRemovePlant::ActionCondition(), ActionDisinfectPlantBit::ActionCondition(), ItemBase::CreatePlant(), ItemBase::EEItemAttached(), CAContinuousWaterPlant::Execute(), ItemBase::GetSlotIndexByPlant(), ActionHarvestCrops::OnActionInfoUpdate(), ActionDisinfectPlantBit::OnExecuteServer(), ActionWaterPlant::OnFinishProgressClient(), ActionWaterPlant::OnFinishProgressServer(), PluginBase::OnRPCHorticultUpdate(), PluginBase::OnRPCHorticultureSpeed(), ItemBase::PrintSlots(), ItemBase::RemoveSlot(), HudDebugWinHorticulture::SendRPCSpeed(), HudDebugWinHorticulture::SendRPCUpdate(), CAContinuousDisinfectPlant::Setup(), and CAContinuousWaterPlant::Setup().
PrintValues()
void PrintValues ()
References m_CurrentPlantMaterialQuantity, m_FullMaturityTime, m_GardenBase, m_GrowthStagesCount, m_HasCrops, m_IsInfested, m_PlantState, m_PlantStateIndex, m_Slot, m_SpoilAfterFullMaturityTime, m_SprayQuantity, m_StateChangeTime, m_TimeTracker, and Print().
RemovePlant()
void RemovePlant ()
RemovePlantEx()
void RemovePlantEx (vector pos)
References ECE_PLACE_ON_SURFACE, GetGame(), m_CurrentPlantMaterialQuantity, RemoveSlot(), ItemBase::SetQuantity(), and UnlockFromParent().
RemoveSlot()
void RemoveSlot ()
Referenced by DestroyPlant(), RemovePlantEx(), ItemBase::RemoveSlotPlant(), and Tick().
SetActions()
override void SetActions ()
References AddAction().
SetDry()
void SetDry ()
References m_PlantState, m_PlantStateIndex, SetPlantState(), and UpdatePlant().
Referenced by GrowthTimerTick().
SetGarden()
void SetGarden (GardenBase gardenBase)
References m_GardenBase.
SetPlantState()
void SetPlantState (int state)
References m_PlantState, and m_TimeTracker.
Referenced by GrowthTimerTick(), Init(), SetDry(), and SetSpoiled().
SetSlot()
void SetSlot (Slot slot)
References m_Slot.
Referenced by OnStoreLoad().
SetSpoiled()
void SetSpoiled ()
References m_PlantState, m_PlantStateIndex, SetPlantState(), and UpdatePlant().
Referenced by Tick().
SpoiledRemoveTimerTick()
void SpoiledRemoveTimerTick ()
SprayPlant()
void SprayPlant (float consumed_quantity)
References ChangeInfestation(), m_InfestationChance, m_IsInfested, m_SprayQuantity, m_SprayUsage, and UpdatePlant().
StopInfestation()
string StopInfestation (float consumed_quantity)
Tick()
void Tick ()
References GrowthTimerTick(), m_DebugTickSpeedMultiplier, m_DeleteDryPlantTime, m_PlantState, m_SpoilAfterFullMaturityTime, m_SpoiledRemoveTime, m_StateChangeTime, m_TimeTicker, m_TimeTracker, RemoveSlot(), and SetSpoiled().
UpdatePlant()
void UpdatePlant ()
References HasCrops(), m_CurrentPlantMaterialQuantity, m_PlantMaterialMultiplier, m_PlantStateIndex, and ToStringLen().
Referenced by GrowthTimerTick(), Harvest(), OnStoreLoadCustom(), SetDry(), SetSpoiled(), and SprayPlant().
~PlantBase()
void ~PlantBase ()
References DestroyPlant(), IsPendingDeletion(), m_MarkForDeletion, m_TimeTicker, and Timer::Stop().
Variable Documentation
m_CropsCount
private int m_CropsCount
Referenced by Harvest(), Init(), OnStoreLoadCustom(), OnStoreSaveCustom(), and PlantBase().
m_CropsType
private string m_CropsType
Referenced by GetCropsType(), Harvest(), OnStoreLoadCustom(), OnStoreSaveCustom(), and PlantBase().
m_CurrentPlantMaterialQuantity
private float m_CurrentPlantMaterialQuantity
Referenced by OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), PrintValues(), RemovePlantEx(), and UpdatePlant().
m_DebugDeleteDryTime
int m_DebugDeleteDryTime static
Referenced by DebugSetGlobalTimes(), and Init().
m_DebugFullMaturityTime
int m_DebugFullMaturityTime static
Referenced by DebugSetGlobalTimes(), and Init().
m_DebugSpoilRemoveTime
int m_DebugSpoilRemoveTime static
Referenced by DebugSetGlobalTimes(), and Init().
m_DebugSpoilTime
int m_DebugSpoilTime static
Referenced by DebugSetGlobalTimes(), and Init().
m_DebugTickSpeedMultiplier
float m_DebugTickSpeedMultiplier = 1 static
Referenced by DebugSetTickSpeedMultiplier(), and Tick().
m_DeleteDryPlantTime
int m_DeleteDryPlantTime
Referenced by DebugSetTimes(), Init(), OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), and Tick().
m_DeleteDryPlantTimer
ref Timer m_DeleteDryPlantTimer
m_FullMaturityTime
int m_FullMaturityTime
Referenced by DebugSetTimes(), Init(), OnStoreLoadCustom(), OnStoreSaveCustom(), Plant_Pepper::Plant_Pepper(), Plant_Potato::Plant_Potato(), Plant_Pumpkin::Plant_Pumpkin(), Plant_Tomato::Plant_Tomato(), Plant_Zucchini::Plant_Zucchini(), and PrintValues().
m_GardenBase
private GardenBase m_GardenBase = NULL
Referenced by GetGarden(), Harvest(), Init(), PrintValues(), and SetGarden().
m_GrowthStagesCount
private int m_GrowthStagesCount
Referenced by DebugSetTimes(), GrowthTimerTick(), Init(), OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), and PrintValues().
m_GrowthTimer
ref Timer m_GrowthTimer
m_HasCrops
private bool m_HasCrops
Referenced by Harvest(), HasCrops(), IsHarvestable(), OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), and PrintValues().
m_InfestationChance
private float m_InfestationChance
Referenced by GrowthTimerTick(), OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), and SprayPlant().
m_InfestationTimer
ref Timer m_InfestationTimer
m_IsInfested
private bool m_IsInfested
Referenced by ChangeInfestation(), GrowthTimerTick(), OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), PrintValues(), and SprayPlant().
m_MarkForDeletion
bool m_MarkForDeletion = false
Referenced by ~PlantBase().
m_ModuleHorticulture
private PluginHorticulture m_ModuleHorticulture
Referenced by ChangeInfestation(), and PlantBase().
m_PlantMaterialMultiplier
private float m_PlantMaterialMultiplier
Referenced by Init(), OnStoreLoadCustom(), OnStoreSaveCustom(), and UpdatePlant().
m_PlantState
protected EPlantState m_PlantState
Referenced by GetPlantState(), Init(), IsHarvestable(), IsSprayable(), NeedsWater(), OnStoreLoadCustom(), OnStoreSaveCustom(), PrintValues(), SetDry(), SetPlantState(), SetSpoiled(), and Tick().
m_PlantStateIndex
private int m_PlantStateIndex
Referenced by GetPlantStateIndex(), GrowthTimerTick(), OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), PrintValues(), SetDry(), SetSpoiled(), and UpdatePlant().
m_Slot
private ref Slot m_Slot = NULL
Referenced by GetSlot(), NeedsWater(), PrintValues(), and SetSlot().
m_SpoilAfterFullMaturityTime
int m_SpoilAfterFullMaturityTime
Referenced by DebugSetTimes(), Init(), OnStoreLoadCustom(), OnStoreSaveCustom(), PrintValues(), and Tick().
m_SpoilAfterFullMaturityTimer
ref Timer m_SpoilAfterFullMaturityTimer
m_SpoiledRemoveTime
int m_SpoiledRemoveTime
Referenced by DebugSetTimes(), Init(), OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), and Tick().
m_SpoiledRemoveTimer
ref Timer m_SpoiledRemoveTimer
m_SprayQuantity
private float m_SprayQuantity
Referenced by GetSprayQuantity(), IsSprayable(), OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), PrintValues(), and SprayPlant().
m_SprayUsage
enum EPlantState m_SprayUsage
Referenced by GetSprayUsage(), IsSprayable(), OnStoreLoadCustom(), OnStoreSaveCustom(), PlantBase(), and SprayPlant().
m_StateChangeTime
float m_StateChangeTime
Referenced by DebugSetTimes(), Init(), OnStoreLoadCustom(), OnStoreSaveCustom(), PrintValues(), and Tick().
m_TimeTicker
protected ref Timer m_TimeTicker
Referenced by PlantBase(), Tick(), and ~PlantBase().
m_TimeTracker
protected float m_TimeTracker
Referenced by GrowthTimerTick(), OnStoreLoadCustom(), OnStoreSaveCustom(), PrintValues(), SetPlantState(), and Tick().
SPOIL_AFTER_MATURITY_TIME
private const float SPOIL_AFTER_MATURITY_TIME = 14400.0
Referenced by Init().
STATE_DRY
const int STATE_DRY = 0 static
STATE_GROWING
const int STATE_GROWING = 1 static
STATE_MATURE
const int STATE_MATURE = 2 static
STATE_SPOILED
const int STATE_SPOILED = 3 static
TICK_FREQUENCY
private const int TICK_FREQUENCY = 1
Referenced by PlantBase().