DayZ Scripts: DebugMonitor Class Reference
DebugMonitor Class Reference
Private Member Functions
void DebugMonitor ()
void Init ()
void SetHealth (float value)
void SetBlood (float value)
void SetLastDamage (string value)
void SetFramerate (float current, float min, float max, float avg)
protected void SetFramerateText (TextWidget widget, float value)
void SetPosition (vector value)
void Show ()
void Hide ()
string CalculateMapTile (vector pos)
int GetTileFomFraction (float fraction)
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
bool IsVisible ()
Private Attributes
protected bool m_IsUsingKBM
private Widget m_WidgetRoot
private TextWidget m_WindowLabelText
private TextWidget m_VersionValue
private TextWidget m_HealthValue
private TextWidget m_BloodValue
private TextWidget m_DmgSourceValue
private TextWidget m_MapTileValue
private TextWidget m_PositionValue
private TextWidget m_CopyPositionInfo
private TextWidget m_FPSValue
private TextWidget m_FPSMinValue
private TextWidget m_FPSMaxValue
private TextWidget m_FPSAvgValue
private int m_FPSTextDefaultColor
Constructor & Destructor Documentation
DebugMonitor()
void DebugMonitor () inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_BloodValue, m_CopyPositionInfo, m_DmgSourceValue, m_FPSAvgValue, m_FPSMaxValue, m_FPSMinValue, m_FPSTextDefaultColor, m_FPSValue, m_HealthValue, m_MapTileValue, m_PositionValue, m_VersionValue, and m_WidgetRoot.
Member Function Documentation
CalculateMapTile()
string CalculateMapTile (vector pos) inline private
References GetGame(), GetTileFomFraction(), CGame::GetWorld(), World::GetWorldSize(), and Math::InverseLerp().
Referenced by SetPosition().
GetTileFomFraction()
int GetTileFomFraction (float fraction) inline private
Referenced by CalculateMapTile().
Hide()
void Hide () inline private
References m_WidgetRoot.
Init()
void Init () inline private
References g_Game, GetGame(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), ScriptInvoker::Insert(), m_IsUsingKBM, m_VersionValue, m_WidgetRoot, and OnInputDeviceChanged().
IsVisible()
bool IsVisible () inline private
References m_WidgetRoot.
OnInputDeviceChanged()
void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
References m_IsUsingKBM.
Referenced by Init().
SetBlood()
void SetBlood (float value) inline private
References m_BloodValue, and float::ToString().
SetFramerate()
void SetFramerate (float current, float min, float max, float avg) inline private
Update the framerate values displayed within the debug monitor with new ones.
References m_FPSAvgValue, m_FPSMaxValue, m_FPSMinValue, m_FPSValue, and SetFramerateText().
SetFramerateText()
protected void SetFramerateText (TextWidget widget, float value) inline private
Sets the provided text widget to display framerate value. Formats and colors the widget according to the value.
References COLOR_RED, COLOR_YELLOW, m_FPSTextDefaultColor, and Math::Round().
Referenced by SetFramerate().
SetHealth()
void SetHealth (float value) inline private
References m_HealthValue, and float::ToString().
SetLastDamage()
void SetLastDamage (string value) inline private
References m_DmgSourceValue.
SetPosition()
void SetPosition (vector value) inline private
References CalculateMapTile(), CGame::CopyToClipboard(), GetGame(), GetUApi(), m_CopyPositionInfo, m_IsUsingKBM, m_MapTileValue, m_PositionValue, ToString(), and vector::ToString().
Show()
void Show () inline private
References m_WidgetRoot.
Field Documentation
m_BloodValue
private TextWidget m_BloodValue private
Referenced by DebugMonitor(), and SetBlood().
m_CopyPositionInfo
private TextWidget m_CopyPositionInfo private
Referenced by DebugMonitor(), and SetPosition().
m_DmgSourceValue
private TextWidget m_DmgSourceValue private
Referenced by DebugMonitor(), and SetLastDamage().
m_FPSAvgValue
private TextWidget m_FPSAvgValue private
Referenced by DebugMonitor(), and SetFramerate().
m_FPSMaxValue
private TextWidget m_FPSMaxValue private
Referenced by DebugMonitor(), and SetFramerate().
m_FPSMinValue
private TextWidget m_FPSMinValue private
Referenced by DebugMonitor(), and SetFramerate().
m_FPSTextDefaultColor
private int m_FPSTextDefaultColor private
Referenced by DebugMonitor(), and SetFramerateText().
m_FPSValue
private TextWidget m_FPSValue private
Referenced by DebugMonitor(), and SetFramerate().
m_HealthValue
private TextWidget m_HealthValue private
Referenced by DebugMonitor(), and SetHealth().
m_IsUsingKBM
protected bool m_IsUsingKBM private
Referenced by Init(), OnInputDeviceChanged(), and SetPosition().
m_MapTileValue
private TextWidget m_MapTileValue private
Referenced by DebugMonitor(), and SetPosition().
m_PositionValue
private TextWidget m_PositionValue private
Referenced by DebugMonitor(), and SetPosition().
m_VersionValue
private TextWidget m_VersionValue private
Referenced by DebugMonitor(), and Init().
m_WidgetRoot
private Widget m_WidgetRoot private
Referenced by DebugMonitor(), Hide(), Init(), IsVisible(), and Show().
m_WindowLabelText
private TextWidget m_WindowLabelText private
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/DebugMonitor.c