DayZ Scripts: MiscEffects Class Reference
MiscEffects Class Reference
Static Private Member Functions
static void PlayVegetationCollideParticles (Object object, DayZPlayerImplement player)
static protected void UpdateVegeCollisionCooldowns ()
Static Private Attributes
static protected const int VEGE_COLLISION_COOLDOWN = 3000
static protected ref map< Object, float > m_VegeCollideColldowns = new map <Object, float>()
Member Function Documentation
PlayVegetationCollideParticles()
static void PlayVegetationCollideParticles (Object object, DayZPlayerImplement player) inline static private
References CGame::ConfigGetText(), Empty, GetGame(), ParticleList::GetParticleIDByName(), GetWorldTime(), m_VegeCollideColldowns, ParticleManager(), Math::RandomFloat(), and UpdateVegeCollisionCooldowns().
Referenced by DayZPlayer::OnStepEvent().
UpdateVegeCollisionCooldowns()
static protected void UpdateVegeCollisionCooldowns () inline static private
References GetWorldTime(), m_VegeCollideColldowns, and VEGE_COLLISION_COOLDOWN.
Referenced by PlayVegetationCollideParticles().
Field Documentation
m_VegeCollideColldowns
protected ref map<Object, float> m_VegeCollideColldowns = new map <Object, float>() static private
Referenced by PlayVegetationCollideParticles(), and UpdateVegeCollisionCooldowns().
VEGE_COLLISION_COOLDOWN
protected const int VEGE_COLLISION_COOLDOWN = 3000 static private
Referenced by UpdateVegeCollisionCooldowns().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/MiscEffects.c