DayZ Scripts: Blend2D< Class T > Class Reference
Blend2D< Class T > Class Reference
Private Member Functions
void Blend2D ()
void Insert (float posX, float posY, T value)
void Clear ()
T Blend (float posX, float posY)
Private Attributes
private ref array< vector > m_Positions
private ref array< T > m_Values
private ref array< float > m_Weights
Constructor & Destructor Documentation
Blend2D()
void Blend2D () inline private
Create new blend structure.
References m_Values.
Member Function Documentation
Blend()
T Blend (float posX, float posY) inline private
References Math3D::BlendCartesian(), m_Values, and Vector().
Clear()
void Clear () inline private
Empty the blend structure.
References m_Values.
Insert()
void Insert (float posX, float posY, T value) inline private
Insert new value at coordinate [posX, posY].
References m_Values, and Vector().
Field Documentation
m_Positions
private ref array<vector> m_Positions private
m_Values
private ref array<T> m_Values private
m_Weights
private ref array<float> m_Weights private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/Blend2D.c