DayZ Scripts: P:/scripts/4_World/Entities/ItemBase/Inventory_Base/Optics.c File Reference
Optics.c File Reference
Data Structures
class Crossbow_RedpointOptic
class LongrangeOptic
class SportingOptic
class PistolOptic
class GrozaOptic
class ACOGOptic
class ACOGOptic_6x
class KashtanOptic
class M68Optic
class FNP45_MRDSOptic
class KobraOptic
class StarlightOptic
class MK4Optic_Tan
class MK4Optic_Black
class MK4Optic_Green
Functions
M68Optic ItemOptics IsSightOnly ()
KobraOptic ItemOptics InitOpticMode ()
override int GetCurrentNVType ()
override void OnOpticModeChange ()
override void OnOpticEnter ()
override void UpdateSelectionVisibility ()
override void SetActions ()
Variables
StarlightOptic ItemOptics
Function Documentation
GetCurrentNVType()
override int GetCurrentNVType ()
References Error(), ItemOptics::IsWorking(), GameConstants::OPTICS_STATE_DAY, and GameConstants::OPTICS_STATE_NIGHTVISION.
InitOpticMode()
KobraOptic ItemOptics InitOpticMode ()
IsSightOnly()
override bool IsSightOnly ()
OnOpticEnter()
override void OnOpticEnter ()
References ItemOptics::HideSelection().
OnOpticModeChange()
override void OnOpticModeChange ()
References ItemOptics::UpdateSelectionVisibility().
SetActions()
override void SetActions ()
References AddAction().
UpdateSelectionVisibility()
override void UpdateSelectionVisibility ()
References ItemOptics::GetCurrentOpticMode(), GetGame(), ItemOptics::HideSelection(), ItemOptics::IsInOptics(), GameConstants::OPTICS_STATE_DAY, GameConstants::OPTICS_STATE_NIGHTVISION, and ItemOptics::ShowSelection().
Variable Documentation
ItemOptics
StarlightOptic ItemOptics