DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionPushCar.c File Reference
ActionPushCar.c File Reference
Data Structures
class ActionPushCarData
class ActionPushCarCB
class ActionPushCarDataReceiveData
Functions
ActionPushCarData ActionPushObjectData GetProgressWidgetMultiplier ()
ActionPushCarCB ActionPushObjectCB ActionPushCar ()
override void CreateActionComponent ()
override protected void ApplyForce (ActionPushObjectData actionData)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override ActionData CreateActionData ()
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
protected float GetDirectionDot (Object target, EntityAI player)
private CarScript GetCar (ActionTarget target)
DEPRECATED.
Variables
int m_PushDirection = -1
float m_HorizontalDirectionRandom = 1.0
float m_VerticalDirectionRandom = 1.0
CarScript m_Car
protected float PUSH_FORCE_IMPULSE_INCREMENT = 200.0
private ActionPushCarData m_ActionDataPushCar
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
References ActionBase::IsInReach(), and UAMaxDistances::SMALL.
ActionPushCar()
ActionPushCarCB ActionPushObjectCB ActionPushCar ()
Referenced by ActionConstructor::RegisterActions(), and SetActions().
ApplyForce()
override protected void ApplyForce (ActionPushObjectData actionData)
Referenced by ProgressActionComponent().
CreateActionComponent()
override void CreateActionComponent ()
CreateActionData()
override ActionData CreateActionData ()
GetCar()
private CarScript GetCar (ActionTarget target)
DEPRECATED.
References ActionPushObject::GetPushObject().
GetDirectionDot()
protected float GetDirectionDot (Object target, EntityAI player)
References vector::Dot().
Referenced by OnStartServer().
GetProgressWidgetMultiplier()
ActionPushCarData ActionPushObjectData GetProgressWidgetMultiplier ()
OnEndServer()
override void OnEndServer (ActionData action_data)
OnStartServer()
override void OnStartServer (ActionData action_data)
References GetDirectionDot(), and ActionPushCarData::m_PushDirection.
Variable Documentation
m_ActionDataPushCar
private ActionPushCarData m_ActionDataPushCar
m_Car
CarScript m_Car
m_HorizontalDirectionRandom
float m_HorizontalDirectionRandom = 1.0
m_PushDirection
int m_PushDirection = -1
m_VerticalDirectionRandom
float m_VerticalDirectionRandom = 1.0
PUSH_FORCE_IMPULSE_INCREMENT
protected float PUSH_FORCE_IMPULSE_INCREMENT = 200.0