DayZ Scripts: HudDebugWinHorticulture Class Reference
HudDebugWinHorticulture Class Reference
Private Member Functions
void HudDebugWinHorticulture (Widget widget_root)
override int GetType ()
override void Show ()
bool OnClick (Widget w, int x, int y, int button)
Called from HudDebug.c.
protected void SendRPCSpeed (float multiplier)
protected void SendRPCUpdate (bool isTarget)
Private Attributes
protected EditBoxWidget m_FullMaturityEditBox
protected EditBoxWidget m_SpoilEditBox
protected EditBoxWidget m_SpoilRemoveEditBox
protected EditBoxWidget m_DryRemoveEditBox
protected EditBoxWidget m_SetAllEditBox
protected EditBoxWidget m_SpeedEditBox
protected ButtonWidget m_ButtonUpdate
protected ButtonWidget m_ButtonUpdateTarget
protected ButtonWidget m_ButtonReset
protected ButtonWidget m_ButtonSetAll
protected ButtonWidget m_ButtonSpeed
protected PluginDeveloperSync m_DevSyncPlugin
Constructor & Destructor Documentation
HudDebugWinHorticulture()
void HudDebugWinHorticulture (Widget widget_root) inline private
References HudDebugWinBase::m_WgtRoot.
Member Function Documentation
GetType()
override int GetType () inline private
References HudDebug().
OnClick()
bool OnClick (Widget w, int x, int y, int button) inline private
Called from HudDebug.c.
References m_ButtonReset, m_ButtonSetAll, m_ButtonSpeed, m_ButtonUpdate, m_ButtonUpdateTarget, m_DryRemoveEditBox, m_FullMaturityEditBox, m_SetAllEditBox, m_SpeedEditBox, m_SpoilEditBox, m_SpoilRemoveEditBox, HudDebugWinBase::m_WgtRoot, SendRPCSpeed(), and SendRPCUpdate().
Referenced by OnClick().
SendRPCSpeed()
protected void SendRPCSpeed (float multiplier) inline private
References Math::Clamp(), GetGame(), GetPlayer(), and PlantBase().
Referenced by OnClick().
SendRPCUpdate()
protected void SendRPCUpdate (bool isTarget) inline private
References ActionTarget, GetGame(), GetPlayer(), m_DryRemoveEditBox, m_FullMaturityEditBox, m_SpoilEditBox, m_SpoilRemoveEditBox, and PlantBase().
Referenced by OnClick().
Show()
override void Show () inline private
References GetPlugin(), and m_DevSyncPlugin.
Field Documentation
m_ButtonReset
protected ButtonWidget m_ButtonReset private
Referenced by OnClick().
m_ButtonSetAll
protected ButtonWidget m_ButtonSetAll private
Referenced by OnClick().
m_ButtonSpeed
protected ButtonWidget m_ButtonSpeed private
Referenced by OnClick().
m_ButtonUpdate
protected ButtonWidget m_ButtonUpdate private
Referenced by OnClick().
m_ButtonUpdateTarget
protected ButtonWidget m_ButtonUpdateTarget private
Referenced by OnClick().
m_DevSyncPlugin
protected PluginDeveloperSync m_DevSyncPlugin private
Referenced by Show().
m_DryRemoveEditBox
protected EditBoxWidget m_DryRemoveEditBox private
Referenced by OnClick(), and SendRPCUpdate().
m_FullMaturityEditBox
protected EditBoxWidget m_FullMaturityEditBox private
Referenced by OnClick(), and SendRPCUpdate().
m_SetAllEditBox
protected EditBoxWidget m_SetAllEditBox private
Referenced by OnClick().
m_SpeedEditBox
protected EditBoxWidget m_SpeedEditBox private
Referenced by OnClick().
m_SpoilEditBox
protected EditBoxWidget m_SpoilEditBox private
Referenced by OnClick(), and SendRPCUpdate().
m_SpoilRemoveEditBox
protected EditBoxWidget m_SpoilRemoveEditBox private
Referenced by OnClick(), and SendRPCUpdate().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptsHudDebug/HudDebugWinHorticulture.c