DayZ Scripts: MissionBenchmark Class Reference
MissionBenchmark Class Reference
Private Member Functions
void MissionBenchmark ()
void ~MissionBenchmark ()
BenchmarkConfig GetConfig ()
void Start ()
override void OnUpdate (float timeslice)
protected void PreloadUpdate ()
protected void MeasureUpdate (float timeSlice)
protected void DisableWeatherChange ()
protected void AdvanceLocation ()
protected void LerpCamera ()
protected void OnLocationSwitch ()
protected void TeleportToPos (BenchmarkLocation loc)
protected void OnBenchmarkEnd (string reason)
protected void CreatePlayer ()
protected void CreateCSVLog ()
protected void FPSLog (string position, float frames)
Static Private Member Functions
static MissionBenchmark GetInstance ()
Private Attributes
protected const int INITIAL_PRELOAD = 5
protected const float STEP_INTERVAL = 1
protected bool m_InitialLoadDone
protected bool m_IsPreloading
protected bool m_LocationDone
protected int m_LocIndex
protected int m_MeasuringStep
protected float m_MeasureStepTimer = 1
protected float m_SumFPS
protected float m_TimeCounter
protected float m_MeasureLength
protected float m_StepDistance
protected FileHandle m_CSVLog
protected BenchmarkLocation m_CurrentLocation
protected BenchmarkLocation m_NextLocation
protected ref BenchmarkConfig m_Config
Static Private Attributes
static protected MissionBenchmark m_Instance
Constructor & Destructor Documentation
MissionBenchmark()
void MissionBenchmark () inline private
References m_Instance.
~MissionBenchmark()
void ~MissionBenchmark () inline private
References m_Instance.
Member Function Documentation
AdvanceLocation()
protected void AdvanceLocation () inline private
References FPSLog(), m_Config, BenchmarkLocation::m_IsDummyWait, m_LocIndex, m_MeasuringStep, BenchmarkLocation::m_Name, m_NextLocation, m_SumFPS, m_TimeCounter, OnLocationSwitch(), and Print().
Referenced by LerpCamera().
CreateCSVLog()
protected void CreateCSVLog () inline private
References FPrintln(), m_Config, m_CSVLog, OnBenchmarkEnd(), OpenFile(), and Print().
Referenced by Start().
CreatePlayer()
protected void CreatePlayer () inline private
References CGame::CreatePlayer(), GetGame(), m_CurrentLocation, BenchmarkLocation::m_StartPos, and CGame::SelectPlayer().
Referenced by OnLocationSwitch().
DisableWeatherChange()
protected void DisableWeatherChange () inline private
References GetGame(), CGame::GetWeather(), Weather::SetDynVolFogDistanceDensity(), Weather::SetDynVolFogHeightBias(), Weather::SetDynVolFogHeightDensity(), and Weather::SetWeatherUpdateFreeze().
Referenced by Start().
FPSLog()
protected void FPSLog (string position, float frames) inline private
References FPrintln(), GetHourMinuteSecondUTC(), GetYearMonthDay(), m_Config, m_CSVLog, and PrintToRPT().
Referenced by AdvanceLocation().
GetConfig()
BenchmarkConfig GetConfig () inline private
References m_Config.
GetInstance()
static MissionBenchmark GetInstance () inline static private
References m_Instance.
LerpCamera()
protected void LerpCamera () inline private
References AdvanceLocation(), Math::Lerp(), BenchmarkLocation::m_CamSpeedMultiplier, m_CurrentLocation, BenchmarkLocation::m_IsDummyWait, m_NextLocation, BenchmarkLocation::m_StartLookAtPos, BenchmarkLocation::m_StartPos, m_StepDistance, m_TimeCounter, and Vector().
Referenced by MeasureUpdate().
MeasureUpdate()
protected void MeasureUpdate (float timeSlice) inline private
References CGame::GetFps(), GetGame(), CGame::GetPlayer(), LerpCamera(), m_Config, m_MeasureStepTimer, m_MeasuringStep, m_SumFPS, Print(), and STEP_INTERVAL.
Referenced by OnUpdate().
OnBenchmarkEnd()
protected void OnBenchmarkEnd (string reason) inline private
References CloseFile(), GetGame(), IDC_MAIN_QUIT, m_Config, m_CSVLog, Print(), and CGame::RequestExit().
Referenced by CreateCSVLog(), OnLocationSwitch(), and Start().
OnLocationSwitch()
protected void OnLocationSwitch () inline private
References CreatePlayer(), vector::Distance(), GetGame(), GetPlayer(), m_Config, m_CurrentLocation, BenchmarkLocation::m_IsDummyTeleport, BenchmarkLocation::m_IsDummyWait, m_LocIndex, m_MeasureStepTimer, m_MeasuringStep, BenchmarkLocation::m_Name, m_NextLocation, BenchmarkLocation::m_StartLookAtPos, BenchmarkLocation::m_StartPos, m_StepDistance, m_SumFPS, m_TimeCounter, OnBenchmarkEnd(), Print(), and TeleportToPos().
Referenced by AdvanceLocation(), and Start().
OnUpdate()
override void OnUpdate (float timeslice) inline private
References m_Config, m_CurrentLocation, m_IsPreloading, m_TimeCounter, MeasureUpdate(), and PreloadUpdate().
PreloadUpdate()
protected void PreloadUpdate () inline private
References INITIAL_PRELOAD, m_Config, m_InitialLoadDone, m_IsPreloading, and m_TimeCounter.
Referenced by OnUpdate().
Start()
void Start () inline private
References CreateCSVLog(), DisableWeatherChange(), m_Config, m_IsPreloading, OnBenchmarkEnd(), and OnLocationSwitch().
TeleportToPos()
protected void TeleportToPos (BenchmarkLocation loc) inline private
References GetGame(), CGame::GetPlayer(), m_CurrentLocation, m_IsPreloading, BenchmarkLocation::m_StartLookAtPos, and BenchmarkLocation::m_StartPos.
Referenced by OnLocationSwitch().
Field Documentation
INITIAL_PRELOAD
protected const int INITIAL_PRELOAD = 5 private
Referenced by PreloadUpdate().
m_Config
protected ref BenchmarkConfig m_Config private
Referenced by AdvanceLocation(), CreateCSVLog(), FPSLog(), GetConfig(), MeasureUpdate(), OnBenchmarkEnd(), OnLocationSwitch(), OnUpdate(), PreloadUpdate(), and Start().
m_CSVLog
protected FileHandle m_CSVLog private
Referenced by CreateCSVLog(), FPSLog(), and OnBenchmarkEnd().
m_CurrentLocation
protected BenchmarkLocation m_CurrentLocation private
Referenced by CreatePlayer(), LerpCamera(), OnLocationSwitch(), OnUpdate(), and TeleportToPos().
m_InitialLoadDone
protected bool m_InitialLoadDone private
Referenced by PreloadUpdate().
m_Instance
protected MissionBenchmark m_Instance static private
Referenced by GetInstance(), MissionBenchmark(), and ~MissionBenchmark().
m_IsPreloading
protected bool m_IsPreloading private
Referenced by OnUpdate(), PreloadUpdate(), Start(), and TeleportToPos().
m_LocationDone
protected bool m_LocationDone private
m_LocIndex
protected int m_LocIndex private
Referenced by AdvanceLocation(), and OnLocationSwitch().
m_MeasureLength
protected float m_MeasureLength private
m_MeasureStepTimer
protected float m_MeasureStepTimer = 1 private
Referenced by MeasureUpdate(), and OnLocationSwitch().
m_MeasuringStep
protected int m_MeasuringStep private
Referenced by AdvanceLocation(), MeasureUpdate(), and OnLocationSwitch().
m_NextLocation
protected BenchmarkLocation m_NextLocation private
Referenced by AdvanceLocation(), LerpCamera(), and OnLocationSwitch().
m_StepDistance
protected float m_StepDistance private
Referenced by LerpCamera(), and OnLocationSwitch().
m_SumFPS
protected float m_SumFPS private
Referenced by AdvanceLocation(), MeasureUpdate(), and OnLocationSwitch().
m_TimeCounter
protected float m_TimeCounter private
Referenced by AdvanceLocation(), LerpCamera(), OnLocationSwitch(), OnUpdate(), and PreloadUpdate().
STEP_INTERVAL
protected const float STEP_INTERVAL = 1 private
Referenced by MeasureUpdate().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/mission/MissionBenchmark.c