DayZ Scripts: DimmingConfig Class Reference
DimmingConfig Class Reference
Private Member Functions
void SetRandomBrigthnessLimits (float min, float max)
void SetRandomDimSpeedLimits (float min, float max)
void SetRandomDurationLimits (float min, float max)
void SetRandomBrightenSpeedLimits (float min, float max)
void SetRandomPauseDurationLimits (float min, float max)
void AddDimmingPattern (array< int > brightnessTarget, array< float > dimSpeed, array< float > dimDuration, array< float > brightenSpeed, array< float > pause)
void SetPatternQueueRepeat (int val)
Private Attributes
float m_DimBrigthnessMin = 0.1
float m_DimBrigthnessMax = 1
float m_DimSpeedMin = 0.1
float m_DimSpeedMax = 1
float m_DimBrigthnessDurationMin = 0.1
float m_DimBrigthnessDurationMax = 1
float m_BrightenSpeedMin = 0.1
float m_BrightenSpeedMax = 1
float m_DimBrigthnessPauseMin = 1
float m_DimBrigthnessPauseMax = 4
bool m_UsePatterns
int m_PatternRepeatCount = -1
int m_CurrentPatternID
int m_PatternCount
int m_CurrentEntryID
ref array< ref array< int > > m_BrightnessPatterns = new array<ref array<int>>()
ref array< ref array< float > > m_DimSpeedPatterns = new array<ref array<float>>()
ref array< ref array< float > > m_DurationPatterns = new array<ref array<float>>()
ref array< ref array< float > > m_BrightenSpeedPatterns = new array<ref array<float>>()
ref array< ref array< float > > m_PausePatterns = new array<ref array<float>>()
Member Function Documentation
AddDimmingPattern()
void AddDimmingPattern (array< int > brightnessTarget, array< float > dimSpeed, array< float > dimDuration, array< float > brightenSpeed, array< float > pause) inline private
References ErrorEx, m_BrightenSpeedPatterns, m_BrightnessPatterns, m_DimSpeedPatterns, m_DurationPatterns, m_PatternCount, m_PausePatterns, and ToString().
Referenced by PointLightBase::BuoyLight(), and PointLightBase::WarheadStorageLight().
SetPatternQueueRepeat()
void SetPatternQueueRepeat (int val) inline private
References m_PatternRepeatCount.
Referenced by PointLightBase::BuoyLight().
SetRandomBrightenSpeedLimits()
void SetRandomBrightenSpeedLimits (float min, float max) inline private
References Math::Clamp(), m_BrightenSpeedMax, and m_BrightenSpeedMin.
SetRandomBrigthnessLimits()
void SetRandomBrigthnessLimits (float min, float max) inline private
References Math::Clamp(), m_DimBrigthnessMax, and m_DimBrigthnessMin.
SetRandomDimSpeedLimits()
void SetRandomDimSpeedLimits (float min, float max) inline private
References Math::Clamp(), m_DimSpeedMax, and m_DimSpeedMin.
SetRandomDurationLimits()
void SetRandomDurationLimits (float min, float max) inline private
References Math::Clamp(), m_DimBrigthnessDurationMax, and m_DimBrigthnessDurationMin.
SetRandomPauseDurationLimits()
void SetRandomPauseDurationLimits (float min, float max) inline private
References Math::Clamp(), m_DimBrigthnessPauseMax, and m_DimBrigthnessPauseMin.
Field Documentation
m_BrightenSpeedMax
float m_BrightenSpeedMax = 1 private
Referenced by AdvanceState(), and SetRandomBrightenSpeedLimits().
m_BrightenSpeedMin
float m_BrightenSpeedMin = 0.1 private
Referenced by AdvanceState(), and SetRandomBrightenSpeedLimits().
m_BrightenSpeedPatterns
ref array<ref array<float> > m_BrightenSpeedPatterns = new array<ref array<float>>() private
Referenced by AddDimmingPattern(), and AdvanceState().
m_BrightnessPatterns
ref array<ref array<int> > m_BrightnessPatterns = new array<ref array<int>>() private
Referenced by AddDimmingPattern(), AdvanceState(), and SelectPattern().
m_CurrentEntryID
int m_CurrentEntryID private
m_CurrentPatternID
int m_CurrentPatternID private
m_DimBrigthnessDurationMax
float m_DimBrigthnessDurationMax = 1 private
Referenced by SetRandomDurationLimits().
m_DimBrigthnessDurationMin
float m_DimBrigthnessDurationMin = 0.1 private
Referenced by AdvanceState(), and SetRandomDurationLimits().
m_DimBrigthnessMax
float m_DimBrigthnessMax = 1 private
Referenced by AdvanceState(), and SetRandomBrigthnessLimits().
m_DimBrigthnessMin
float m_DimBrigthnessMin = 0.1 private
Referenced by AdvanceState(), and SetRandomBrigthnessLimits().
m_DimBrigthnessPauseMax
float m_DimBrigthnessPauseMax = 4 private
Referenced by AdvanceState(), and SetRandomPauseDurationLimits().
m_DimBrigthnessPauseMin
float m_DimBrigthnessPauseMin = 1 private
Referenced by AdvanceState(), and SetRandomPauseDurationLimits().
m_DimSpeedMax
float m_DimSpeedMax = 1 private
Referenced by AdvanceState(), and SetRandomDimSpeedLimits().
m_DimSpeedMin
float m_DimSpeedMin = 0.1 private
Referenced by AdvanceState(), and SetRandomDimSpeedLimits().
m_DimSpeedPatterns
ref array<ref array<float> > m_DimSpeedPatterns = new array<ref array<float>>() private
Referenced by AddDimmingPattern(), and AdvanceState().
m_DurationPatterns
ref array<ref array<float> > m_DurationPatterns = new array<ref array<float>>() private
Referenced by AddDimmingPattern(), and AdvanceState().
m_PatternCount
int m_PatternCount private
Referenced by AddDimmingPattern(), and SelectPattern().
m_PatternRepeatCount
int m_PatternRepeatCount = -1 private
Referenced by SelectPattern(), and SetPatternQueueRepeat().
m_PausePatterns
ref array<ref array<float> > m_PausePatterns = new array<ref array<float>>() private
Referenced by AddDimmingPattern(), and AdvanceState().
m_UsePatterns
bool m_UsePatterns private
Referenced by AdvanceState().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ScriptedLightBase/Dimming/DimmingConfig.c