DayZ Scripts: AutotestConfigHandler Class Reference
AutotestConfigHandler Class Reference
Static Private Member Functions
static bool LoadData (string path)
static set< string > GetSuites ()
Static Private Attributes
static ref AutotestConfigJson m_Data = new AutotestConfigJson()
Member Function Documentation
GetSuites()
static set< string > GetSuites () inline static private
References m_Data, and AutotestConfigJson::TestSuites.
Referenced by AutotestRunner::Start().
LoadData()
static bool LoadData (string path) inline static private
References AutoTestFixture::LogRPT(), m_Data, and path.
Referenced by CGame::AutoTestLaunch().
Field Documentation
m_Data
ref AutotestConfigJson m_Data = new AutotestConfigJson() static private
Referenced by GetSuites(), and LoadData().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Autotest/AutotestConfigHandler.c